peer-42seoul/Peer-Frontend

peer_web_frontend/src/components/MessageContent.tsx
peer_web_frontend/src/components/MessageList.server.tsx

쪽지 기능 컴포넌트 MessageList, MessageContent 컴포넌트 추가했습니다.

[C-MYPAGE] 쪽지

---

peer_web_frontend/src/app/login/page.tsx
peer_web_frontend/src/states/useAuthStore.tsx
peer_web_frontend/tsconfig.json

Chore: add zustand store folder

---

peer_web_frontend/src/app/layout.tsx
peer_web_frontend/src/app/page.tsx
peer_web_frontend/src/app/panel/NavBar.tsx
peer_web_frontend/src/app/panel/OptionDetail.tsx
peer_web_frontend/src/app/panel/OptionSort.tsx
peer_web_frontend/src/app/panel/ProjectCard.tsx
peer_web_frontend/styles/global.css
peer_web_frontend/styles/reset.css

1. 와이어프레임에 맞춰 메인페이지 요소를 구현했습니다. layout 부분과 기능 부분은 다음 pr 때 추가될 예정입니다~
floating 버튼이 nav바와 겹쳐져있는건 의도한게 아닙니다... 다음번에 수정될 예정입니다.
2. Nav바가 리다이렉트되도록 설정했습니다.

[C-MAIN] 메인 페이지 요소 구현

---

peer_web_frontend/src/app/profile/MyPage/page.tsx
peer_web_frontend/src/app/profile/MyPage/panel/ProfileLinksSection.tsx

1. 유저 링크 모듈을 다른 컴포넌트로 분리하였습니다.
2. 기본 html 태그를 mui로 바꾸었습니다.

[C-MYPAGE-20, 21, 23] 유저 링크 모듈

---

peer_web_frontend/src/app/profile/MyPage/page.tsx
peer_web_frontend/src/app/profile/MyPage/panel/ProfileCard.tsx
peer_web_frontend/src/app/profile/MyPage/panel/ProfileLinksSection.tsx
peer_web_frontend/src/app/profile/MyPage/panel/ProfileSection.tsx
peer_web_frontend/src/types/IUserProfile.ts

ProfileCard에 자기소개를 추가하였습니다. 이후 해당 ui에 디자인을 입힐 때 처리에 덜 어려움을 겪도록 Box 태그로 감싸주었습니다.

[C-MYPAGE-19] 유저 프로필에 자기소개 UI 추가

---

peer_web_frontend/src/app/signup/page.tsx
peer_web_frontend/src/app/signup/panel/EmailField.tsx
peer_web_frontend/src/app/signup/panel/FormField.tsx

이메일 형식이 유효한지 검증하는 로직 추가했습니다.
이메일, 패스워드, 닉네임 등 입력받는 칸 컴포넌트를 분리중입니다. 
백엔드 서버에서도 검증을 받아야되서 서버에서 검증받는 것을 확인하려면 각각의 입력컴포넌트에 useState를 적용시켜야 할 것 같아서
분리하는 게 더 깔끔할 것 같습니다.

[B-INFO] 이메일 형식 검증 로직 추가 및 컴포넌트 분리

---

peer_web_frontend/src/api/fetchers.ts
peer_web_frontend/src/app/page.tsx
peer_web_frontend/src/app/panel/MainPage.tsx
peer_web_frontend/src/app/panel/SearchOption.tsx
peer_web_frontend/src/app/panel/SelectType.tsx

세부 옵션 요소들을 추가했습니다. 
작업스택의 태그들이 밑으로 내려오도록 수정할 예정입니다.
목표기간은 와이어프레임의 변경이 있을 수 있다고 해서, 일단 비워두었습니다~

[C-MAIN] 세부 옵션 요소 추가

---

peer_web_frontend/src/app/privacy/page.tsx

[A-JOI] 개인정보동의서명 페이지

---

peer_web_frontend/src/app/profile/MyPage/panel/ProfileBioEditor.tsx
peer_web_frontend/src/app/profile/MyPage/panel/ProfileLinkEditor.tsx
peer_web_frontend/src/components/CuTextField.tsx
peer_web_frontend/src/components/CuTextFieldLabel.tsx

1. 소개 수정 폼(ProfileBioEditor)의 폼 유효성 검사 기능 추가
2. 링크 수정 폼에 임시적으로 폼 유효성 검사 기능 추가 (디자이너와 레이아웃 수정 관련 논의 필요)
3. 커스텀 TextField에 fullWidth, autoComplete, error등 추가

[Public & C-MYPAGE] CuTextField에 prop 추가 및 수정 모달 추가 구현

---

peer_web_frontend/package-lock.json
peer_web_frontend/package.json
peer_web_frontend/src/app/layout.tsx
peer_web_frontend/src/app/panel/MainCarousel.tsx
peer_web_frontend/src/app/panel/MainPage.tsx
peer_web_frontend/src/app/panel/MainProfile.tsx
peer_web_frontend/src/app/panel/MainShowcase.tsx
peer_web_frontend/src/app/panel/NavBar.tsx
peer_web_frontend/src/app/panel/SearchOption.tsx
peer_web_frontend/src/app/panel/SelectType.tsx

* pc뷰를 따로 생성했습니다. 아예 따로 리턴하는 방식으로 만들었는데, 이 방식보다 더 좋은 방식이 있을 수도 있을 것 같아요. 좋은 아이디어 있으면 말씀부탁드립니다. 
* 배너 캐러셀을 위해 react-slicker라는 라이브러리를 설치했습니다.

[C-MAIN] 메인페이지 pc뷰 추가

---

peer_web_frontend/package-lock.json
peer_web_frontend/package.json
peer_web_frontend/src/app/layout.tsx
peer_web_frontend/src/app/panel/MainCard.tsx
peer_web_frontend/src/app/panel/MainCarousel.tsx
peer_web_frontend/src/app/panel/MainPage.tsx
peer_web_frontend/src/app/panel/SearchOption.tsx
peer_web_frontend/src/hook/useInfiniteScroll.tsx

* InfiniteScroll hook이 추가되었습니다. 
* 아직 잘 작동하는지 완벽하게 테스트하지 못한 상태입니다!! page 변수를 업데이트 시킬때 발생하는 useSWR의 데이터 패칭을 기다려야하는데, 이를 기다리게 하는 적절한 방법을 찾다가 useSWR의 mutate 호출해 기다리는 형식으로 만들었습니다. 참고로 mutate는 데이터를 다시 갱신하는 함수입니다. 하지만 어차피 useSWR에서 page 변수가 변할 때 데이터 패치가 다시 이뤄지므로, 따지고보면 데이터 패칭을 두번하는 꼴이나 다름 없습니다. 근데 방법이 생각나지 않네요. 좋은 아이디어 제시 부탁드립니다.
* 메인페이지 검색이 되도록 수정되었습니다. 검색은 같은 메인페이지에서 이루어집니다.
* +) api 변경에 따라 프로퍼티를 조금 변경했습니다~

[C-MAIN] 무한스크롤 훅 추가, 메인페이지 검색 되도록 수정

---

peer_web_frontend/src/app/profile/layout.tsx
peer_web_frontend/src/app/profile/page.tsx
peer_web_frontend/src/components/CuButton.tsx

1. /profile로 들어갔을 때 pc일 경우 /profile/MyPage로 리다이렉션 시켜줬습니다.
2. 모바일의 경우 마이페이지 화면(프로필 x)을 띄워주도록 하였습니다.

[C-MYPAGE] 모바일 마이페이지 구현

---

peer_web_frontend/src/app/profile/MyPage/panel/ProfileBioEditor.tsx

[C-MYPAGE-2,3,4] 프로필 업로드 기능 구현

---

peer_web_frontend/src/app/panel/NavBar.tsx
peer_web_frontend/src/app/profile/MyPage/panel/ProfileBioEditor.tsx

1. 기본 이미지로 변경하는 기능을 추가하였습니다.
1. 버튼 안에 버튼 컴포넌트가 있어서 나던 에러를 임시로 고쳤습니다.

[C-MYPAGE-4] 기본 이미지로 변경 기능 추가

---

peer_web_frontend/package-lock.json
peer_web_frontend/package.json
peer_web_frontend/src/app/recruitment/page.tsx
peer_web_frontend/src/app/recruitment/panel/SetInterview/Answers.tsx
peer_web_frontend/src/app/recruitment/panel/SetInterview/AreaForAddInterviewForm.tsx
peer_web_frontend/src/app/recruitment/panel/SetInterview/AreaForShowAnswers.tsx
peer_web_frontend/src/app/recruitment/panel/SetInterview/SetInterview.tsx
peer_web_frontend/src/app/recruitment/panel/SetInterview/WriteAnswers.tsx
peer_web_frontend/src/app/recruitment/panel/SetTeamIntroduction/SetTeamIntroduction.tsx
peer_web_frontend/src/app/recruitment/panel/SetTeamTag/TagAutoComplete.tsx

- 선형배율 옵션 추가
- 팀 소개글 react markdown editor 적용완료
- 백엔드 API 와 연동
- 에러코드 (아직 백엔드와 논의중) 확립
- 에러코드에 해당하는 알림 추가 (toastUI 메세지 활용예정)
+ 2,115 라고해도, MarkDown Editor 패키지 설치해서 1800이 늘어난거라 겁먹지 마세요!

[J-TB-0~28] 모집글쓰기 페이지, 선형배율 답변 기능 추가 완료

---

peer_web_frontend/src/app/my-page/privacy/page.tsx
peer_web_frontend/src/app/my-page/privacy/panel/ModifyInfoModal.tsx

- 마이페이지에서 개인정보 페이지 추가했습니다.
- 개인정보 변경 모달 만드는 중입니다.

[C-MYPAGE] 개인정보 페이지 추가

---

peer_web_frontend/src/api/config.ts
peer_web_frontend/src/app/find-account/page.tsx
peer_web_frontend/src/app/login/oauth/page.tsx
peer_web_frontend/src/app/login/page.tsx
peer_web_frontend/src/states/useAuthStore.tsx

- axios 통신시에 헤더에 accessToken을 붙여 요청을 보내는 axios interceptor를 작성했습니다.
- 사용자 인증이 필요한 통신에 useAxiosWithAuth를 import하고 const axiosInstance = useAxiosWithAuth()로 인스턴스를 불러와 기존 axios와 동일하게 사용하면 됩니다! (대신 base url은 이미 붙어있기때문에 base url 제외한 endpoint만 넣어주시면 됩니다) 
( + 전역상태에 있던 userId는 accessToken에 이미 암호화상태로 담겨있기때문에 백에서 직접 전달하지 않기로 결정되었습니다..)

[C-SIGN] Axios Interceptor 작성

---

peer_web_frontend/src/app/signup/hook/useSignUpForm.ts

- URL 쿼리에 담긴 소셜로그인 정보를 post할 때 넣어주는 코드를 추가했습니다.

[B-INFO] Oauth 로그인으로 회원가입페이지 들어오는 경우 처리

---

peer_web_frontend/src/app/my-page/privacy/page.tsx
peer_web_frontend/src/app/my-page/privacy/panel/UserInfoEdit.tsx

- 피그마 UI에는 모달이 있는데 이 부분 기획이 변경될 예정이라고 hyna한테 들어서 일단 modal을 삭제했습니다.
- 2스텝 때 지역인증, 42인증이 추가될 때 디자인 작업이 이루어진다고 들어서 차후 개발할 예정입니다.

[C-MYPAGE] 개인정보 페이지 수정 모달 삭제

---

peer_web_frontend/src/app/my-page/privacy/page.tsx
peer_web_frontend/src/app/my-page/privacy/panel/UserInfoEdit.tsx
peer_web_frontend/src/app/my-page/privacy/panel/UserWithdrawalModal.tsx

- 회원탈퇴 모달 추가했습니다.
- woorikim님이 만드신 jsx토큰이 들어있는 axios 훅을 사용했습니다.

[C-MYPAGE] 회원탈퇴 모달 추가

---

peer_web_frontend/src/app/report/page.tsx
peer_web_frontend/src/app/report/panel/ReportForm.tsx

- 신고하기 페이지를 임시로 만들었습니다 (모달 형태가 될 수도 있음)
- 쿼리 스트링으로 신고의 유형과 id를 구분해 post요청 데이터로 보냅니다.

[F-BAN] 신고하기 페이지

---

peer_web_frontend/src/app/my-page/homepage-setting/page.tsx
peer_web_frontend/src/app/my-page/homepage-setting/panel/DisplaySetting.tsx
peer_web_frontend/src/app/my-page/homepage-setting/panel/KeywordSetting.tsx
peer_web_frontend/src/app/my-page/homepage-setting/panel/NotifSetting.tsx

1. 알림 설정 토글을 만들어주었습니다.
2. 화면 스타일 설정 ui를 구현하였습니다.

[C-MYPAGE-25, 29, 30, 31, 67, 68] 홈페이지 설정 페이지 알림 설정, 키워드 알림 설정, 화면 스타일 설정 ui 구현

---

src/app/my-page/homepage-setting/page.tsx
src/app/my-page/homepage-setting/panel/KeywordSetting.tsx
src/app/my-page/homepage-setting/panel/NotifSetting.tsx
src/app/my-page/profile/page.tsx
src/app/my-page/profile/panel/SettingContainer.tsx
src/components/CloseButton.tsx

1. 알림 설정과 알림 키워드 설정에 response에 따른 토스트를 추가하였습니다.

[C-MYPAGE-29,30,31] toast 알람 추가

---

src/app/search/panel/SearchBody.tsx
src/app/search/panel/SearchHistory.tsx

DB에 담을 것도 아니라 판단되어 로컬 스토리지에 최대 5개를 담아서 보여주는 걸로 처리 했습니다.

[C-SRC] 지난 검색어 기능 구현

---

src/components/ImageUploadButton.tsx

1. 기존에 제가 구현해두었던 이미지 업로드 버튼 로직을 공용 컴포넌트로 빼두었습니다
1. js doc으로 주석을 바꿀 예정입니다.

[PUBLIC] 이미지 업로드 버튼 공용 컴포넌트 구현

---

src/api/config.ts
src/states/useAuthStore.tsx

- 백에서 요구하는 로직에 맞게 api 요청 주소와 logout 함수를 수정했습니다.

[C-SIGN] API수정 및 useAuthStore 수정

---

src/api/fetchers.ts

- 로그인 상태(accessToken)이 필요한 get요청에 사용할 수 있도록 getFetcherWithInstance를 작성했습니다.

[C-SIGN] AxiosInterceptor를 사용할 수 있는 getFetcher 추가

---

src/app/find-account/page.tsx
src/app/find-account/panel/SendCodeForm.tsx
src/app/find-account/panel/SendEmailForm.tsx
src/app/login/page.tsx

- 로그인 상태이거나, 로그인이 완료되면 홈"/"으로 이동하도록 수정했습니다
- 비밀번호 찾기 페이지에서 발생하는 오류사항을 고치고 API도 변경사항에 맞게 수정했습니다.

[C-SIGN-01, 03] 로그인 로직, 비밀번호 찾기 페이지 수정

---

src/api/config.ts

- 401에러일 때만 토큰 관련 처리를 하도록 수정했습니다.

[C-SIGN] Axios Interceptor 에러 처리 변경

---

.gitignore
src/app/search/panel/SearchBody.tsx
src/app/search/panel/SearchHistory.tsx

- 지난 검색어 클릭 시 상단의 검색창으로 값이 들어가게 추가!

[C-SRC] 지난 검색어 클릭 액션 추가

---

src/app/signup/page.tsx

[B-INFO] nickname DTO 수정

---

src/app/my-page/interests/page.tsx

- 기존에 타입(스터디, 프로젝트)이 바뀌었을 때 데이터 섞임 문제가 있던 부분을 수정하였습니다.

[C-MYPAGE] 관심 리스트 데이터 섞임 문제 해결

---

src/api/config.ts
src/app/login/page.tsx

- 로그인의 에서 처리 로직을 수정하고 추가로 ReactDom(ununique id) 에러도 고쳤습니다.

[C-SIGN-01] 존재하지 않는 회원 정보로 로그인 시 에러처리 수정

---

src/app/layout.tsx
src/app/my-page/interests/page.tsx
src/app/my-page/profile/page.tsx
src/app/panel/CuSWRConfig.tsx

1. swr이 무한히 요청 보내던 현상을 제거하였습니다.

[C-MYPAGE] swr이 무한히 요청 보내던 현상 제거

---

src/app/my-page/privacy/page.tsx
src/app/my-page/privacy/panel/UserInfoEdit.tsx
src/app/my-page/privacy/panel/UserWithdrawalModal.tsx
src/types/IToastProps.ts

- 개인정보 페이지에서 데이터를 불러올 때 Axiosinstance로 헤더를 토큰을 넣어서 보내게 수정했습니다.
- API 엔드포인트가 잘못된 부분이 있어서 수정했습니다.
- useSWR에서 계속 요청을 보내는 거를 수정했습니다.

[C-MYPAGE] 개인정보 페이지에서 토큰 헤더 추가

---

src/app/search/panel/SearchBody.tsx
src/app/search/panel/SearchHistory.tsx

- 최대 5개 제한
- 추가할 때 마다 오래된 검색어 제거
- 추가할 때도 제대로 들어감

[C-SRC] 지난 검색어 기능 수리

---

src/api/config.ts
src/app/login/page.tsx
src/app/my-page/profile/panel/ProfileCard.tsx
src/states/useAuthStore.tsx

- zustand로 만든 상태 안에서 useCookie hook을 사용할 수 없어 쿠키 삭제를 별도로 처리하도록 로직을 변경했습니다.
- 마이 프로필 페이지에 임시로 로그아웃 버튼을 만들었습니다

[C-SIGN] 로그아웃 과정에서 refreshToken 삭제 방식 변경

---

src/app/team-list/page.tsx
src/app/team-list/panel/Sidebar.tsx
src/app/team-list/panel/TeamsList.tsx
src/app/teams/@setting/[id]/page.tsx
src/app/teams/@setting/[id]/panel/SetupTeam.tsx

[I-TM] 팀페이지 내 id 값 수정

---

src/app/my-page/homepage-setting/panel/KeywordSetting.tsx
src/app/my-page/panel/SubNavBar.tsx

1. SubNavBar 포커싱 오류 처리
2. 전체 삭제 api 처리 로직 변경
#222

[C-MYPAGE] SubNavBar 포커싱 오류 처리, 키워드 세팅 전체 삭제 api 처리 로직 변경

---

src/app/my-page/message/page.tsx
src/app/my-page/message/panel/MessageContainer.tsx
src/app/my-page/message/panel/MessageWritingFormModal.tsx
src/states/useMessageDataState.tsx
src/states/useMessageStore.tsx

close #213
close #229 
- 쪽지 목록 무한요청 버그 수정 (`getFetcherWithInstance`를 사용하던 부분을 삭제했습니다.)
- 새 쪽지 모달이 열리지 않던 버그를 수정했습니다. (props 업데이트가 잘 안되는 이유였음)
- 메시지 목록을 업데이트 해야 하는 부분이 분산되어 있어서 화면에 표시될 메시지 목록을 저장하는 전역 상태를 추가했습니다. (`useMessageDataState`)
- 새 쪽지 모달에서 사용자 검색 결과가 없는 경우에 표시되는 메시지를 추가했습니다.

[C-MYPAGE] 쪽지 api 무한요청 버그 수정 및 쪽지 관련 버그 일부 수정

---

src/app/signup/page.tsx
src/app/signup/panel/PasswordField.tsx

- safari에서 자동으로 암호를 만드는 경우 필드를 삭제할 수가 없어서 필드값을 지우는 버튼을 만들었습니다.
- 회원가입 후 메인페이지로 이동했는데 로그인 페이지로 이동하게 했습니다.

[B-INFO] 회원가입 페이지 x 버튼 추가

---

src/app/my-page/profile/panel/ProfileBioEditor.tsx

1. 요청 본문 타입을 json 객체에서 FormData 객체로 변경하였습니다.
#232 
주전님도 추후에 참고하셔야 할 일이 있을 것 같아 우선 리뷰어로 걸어뒀습니다.

[C-MYPAGE] 프로필 소개 수정 시 전송 본문 타입 변경

---

src/app/signup/page.tsx

- 토스트 메세지 상태관리를 메세지와 에러를 객체로 묶어서 관리합니다.

[B-INFO] 회원가입 토스트 메세지 리펙토링

---

src/app/my-page/profile/page.tsx
src/app/my-page/profile/panel/ProfileCard.tsx

1. 로딩 중에 로그아웃을 할 수 있도록 버튼을 추가하였습니다.
2. 로딩 이후에 보이는 로그아웃 버튼의 위치를 변경하였습니다.

[C-MYPAGE] 프로필 로딩 페이지에 로그아웃 버튼 추가

---

src/app/my-page/interests/page.tsx
src/app/panel/MainCard.tsx
src/app/recruitment/[id]/page.tsx
src/types/IPostDetail.ts

빌드 에러를 수정했습니다. 제가 변수 이름을 잘못 넣었네요...
+ 추가로 IMainCard를 모두 쓸 수 있도록 타입 폴더로 빼놨습니다

빌드 에러 해결: 변수명 수정

---

src/app/my-page/interests/page.tsx
src/app/recruitment/[id]/panel/RecruitFormModal.tsx

[J-TB] 모집글 지원하기 api recruit 스펠링 수정

---

src/app/login/oauth/page.tsx
src/app/login/page.tsx
src/app/my-page/profile/page.tsx
src/states/useAuthStore.tsx

- param으로 받다가 다시 cookie로 받는 걸로 변경

[C-SIGN-04] Oauth 로그인 시 refreshToken 받는 법 수정

---

src/app/my-page/message/[id]/page.tsx
src/app/my-page/message/[id]/panel/MessageForm.tsx
src/app/my-page/message/[id]/panel/MessageFormModal.tsx
src/app/my-page/message/page.tsx
src/app/my-page/message/panel/MessageContainer.tsx
src/app/my-page/message/panel/MessageList.tsx

- PC 화면과 모바일 화면의 새 쪽지 보내기 버튼을 다르게 할 수 있도록 구조 수정
- 모바일 쪽지 대화창에 답하기 버튼, 답하기 모달 추가

[C-MYPAGE] 쪽지 모바일 화면 추가

---

src/app/my-page/homepage-setting/panel/NotifSetting.tsx

1. 키워드 알림을 그리드에서 스택으로 변경하였습니다.

[C-MYPAGE-63~66] 키워드 알림 그리드에서 스택으로 변경

---

src/app/my-page/interests/page.tsx
src/app/my-page/interests/panel/InterestsContents.tsx
src/app/page.tsx
src/app/panel/MainPage.tsx
src/app/panel/MainProfile.tsx
src/app/panel/Options.tsx
src/app/recruitment/[id]/panel/RecruitFormModal.tsx
src/hook/useInfiniteScroll.tsx
styles/global.css

* content라는 변수를 만들어서, 무한 스크롤시 이전 데이터와 새로 불러온 데이터를 합치도록 만들었습니다 
* page가 1일 경우, ssr로 가져온 데이터라고 취급하여 useSWR을 불러오지 않았습니다.
* useInfiniteScrollHook를 만들었습니다
* useInfiniteScroll과 다른 점은 pageLimit가 아닌 isEnd로 마지막을 판단한다는 점입니다
*  useInfiniteScroll를 직접 수정하지 않은 이유는, 이미  useInfiniteScroll를 다른 곳에서 쓰고 있어서 쉽사리 수정하기 힘들었고, useInfiniteScrollHook 역시 아직 테스트가 다 끝난 게 아니라 이후 수정될 가능성이 있어 따로 빼놓았습니다. 추후 기능 테스트가 끝나면 다른 곳에 쓰고 있는 useInfiniteScroll와 useInfiniteScrollHook을 통일 시킬 예정입니다.
* 메인에서 계속 뜨던 hydration 이슈를 수정했습니다. isClient라는 변수를 만들어 수정했습니다~

[C-MAIN] 메인페이지 useSWR 수정, 무한스크롤 훅 개선, 하이드레이션 이슈 수정

---

src/app/find-account/page.tsx
src/app/find-account/panel/FindComplete.tsx
src/app/find-account/panel/SendCodeForm.tsx
src/app/find-account/panel/SendEmailForm.tsx
src/app/recruitment/[id]/panel/LinkButton.tsx

- onSubmit에 async를 적용해 isSubmitting 상태를 버튼의 disabled로 사용하려면 axios 요청시에 await를 사용해야해서 문법을 수정하게 되었습니다.
- 변경된 와이어 프레임에 따라 비밀번호가 재설정 된 후 보여지는 컴포넌트도 추가했습니다.

[C-SIGN-03] formState의 isSubmitting이 제대로 적용되지 않아 요청을 여러번 할 수 있었던 문제 해결

---

src/app/recruitment/[id]/panel/LinkButton.tsx

- 추가로 링크버튼에 onMouseEnter로 popover가 나타났을 때 스크롤바가 사라지면서 화면 비율이 살짝 달라지는 문제도 해결했습니다.

[J-TB-07] 모집글 뷰에 소통도구 링크 클릭 이동이 안되던 문제 해결

---

.gitignore

PWA 관련 파일을 지우고 gitignore를 설정했습니다.

[HOTFIX] add gitignore related to pwa

---

src/app/panel/MainLayout.tsx
src/app/panel/MainPage.tsx
src/app/panel/MuiThemeProvider.tsx
src/app/panel/NavBar.tsx
src/states/useDarkMode.ts

1. primary color를 purple.strong으로 처리하였습니다.
2. 디자이너님이 지정해주신 색을 palette에 추가하였습니다. 
3. 웬만한 컴포넌트에 커스텀 색을 color prop으로 쓸 수 있도록 처리하였습니다.

[PUBLIC] 디자인 색 커스텀 추가

---

src/app/signup/page.tsx

[FIX] 회원가입 페이지의 기본 step number 변경

---

src/app/my-page/privacy/page.tsx
src/app/my-page/privacy/panel/UserInfoEdit.tsx

-링크로 이동하는 소셜 로그인과 달리 소셜 연동 링크자체에 토큰을 담아 get요청을 보내는데 CORS설정이 걸려있어 머지후 테스트가 필요합니다.

[C-SIGN-04] 마이페이지 - 개인정보 페이지에 소셜 계정 연동 버튼 추가

---

src/app/login/oauth/page.tsx
src/app/page.tsx

이전 cookie 설정이 build error가 나서,
cookies-next를 사용하여 구현하는 방식으로 수정해보았습니다
docs를 참고하여 구현했습니다.
https://www.npmjs.com/package/cookies-next

[C-MAIN] cookie 수정

---

src/app/recruit/write/page.tsx

불필요한 추가 state 제거하고 previewImage 를 사용해서 데이터 전송

[J-TB] 모집글쓰기에서 이미지 null 들어가는 문제 해결

---

src/app/login/oauth/ft/page.tsx
src/app/login/oauth/google/page.tsx

[C-SIGN] Oauth 연동 리다이렉션 페이지 수정

---

src/app/my-page/privacy/page.tsx
src/app/my-page/privacy/panel/UserInfoEdit.tsx
src/app/my-page/profile/panel/MyInfoCard.tsx
src/app/my-page/profile/panel/ProfileCard.tsx

- 개인 정보 페이지에 디자인을 적용했습니다.
- 비밀번호 변경 부분은 모달로 변경해야하는데, 후에 모달 컴포넌트가 통일되면 계정 삭제 모달과 함께 수정하도록 하겠습니다.

[C-MYPAGE] 마이페이지 개인정보 페이지 디자인 적용

---

src/app/recruit/[id]/page.tsx

[J-TB] next/image 제거

---

src/app/panel/main-page/Options.tsx
src/app/recruit/write/page.tsx

- 모든 태그를 가져오는 api의 엔드포인트 명을 변경하였습니다.

[HOTFIX] 태그 가져오는 api 엔드 포인트 명 변경

---

src/app/recruit/[id]/edit/panel/SetTeamRole/SetTeamRole.tsx
src/app/recruit/write/page.tsx
src/types/IPostDetail.ts

[HOTFIX] 빌드 시 에러 수정

---

src/app/hitchhiking/panel/CardContainer.tsx

1. 히치하이킹 카드의 배경에 있는 카드를 구현하였습니다.
2. 뭔가 아쉬워서 애니메이션을 적용하였습니다.
3. ~~원래는 토글을 구현하려 하였으나 그것까지 하고 자기는 어려워서 더 가벼운 작업을 진행하였습니다.~~

[H-HITCH] 히치하이킹 카드 배경 적용

---

src/app/recruit/[id]/edit/page.tsx
src/app/recruit/[id]/edit/panel/SetInterview/Answers.tsx
src/app/recruit/[id]/edit/panel/SetInterview/AreaForAddInterviewForm.tsx
src/app/recruit/[id]/edit/panel/SetInterview/AreaForShowAnswers.tsx
src/app/recruit/[id]/edit/panel/SetInterview/WriteAnswers.tsx
src/app/recruit/[id]/edit/panel/SetTeamRole/SetTeamRole.tsx
src/app/recruit/write/page.tsx

- 인터뷰질문삭제안됨, 
- 온라인 선택시 제출안됨
- 그리고 제출시 조건 부문을 좀 더 가독성 좋게 리팩토링 하였음.

[J-TB] 모집글 작성/수정 이슈 해결 (인터뷰질문삭제안됨, 온라인 선택시 제출안됨)

---

src/app/recruit/[id]/page.tsx
src/app/recruit/[id]/panel/ApplyButton.tsx
src/app/recruit/[id]/panel/ApplyDrawerButton.tsx
src/app/recruit/[id]/panel/ApplyMenuButton.tsx
src/app/recruit/[id]/panel/form/RecruitFormModal.tsx
src/types/IPostDetail.ts

* 모집글에 현재 지원상태를 넣었습니다.
* 모집글 버그를 수정했습니다. (https://github.com/peer-42seoul/Peer-Frontend/issues/469)

[J-TB] 모집글에 현재 지원상태 넣기, 모집글 버그 수정

---

.github/workflows/main.yml
.github/workflows/test.yml
package-lock.json

[HOTFIX] 테스트 서버 환경 설정

---

.github/workflows/test.yml

[PUBLIC] 테스트 서버 빌드 중 오타 수정

---

next.config.js
src/api/location.tsx
src/app/search/panel/SearchBody.tsx
src/app/search/panel/SearchHistory.tsx
src/app/teams/[id]/setting/page.tsx
src/app/teams/[id]/setting/panel/ApplicantList.tsx
src/app/teams/[id]/setting/panel/Icons.tsx
src/app/teams/[id]/setting/panel/SetupInfo.tsx
src/app/teams/[id]/setting/panel/SetupMember.tsx
src/app/teams/[id]/setting/panel/TeamJobAdd.tsx

- 저번 PR의 개선할 점을 싹다 고쳤습니다. (몇몇은 제외)
- 팀 역할을 수정하는 기능을 추가했습니다.
- ui 개선을 했습니다.

[I-TM] 팀설정페이지에서 팀 역할 수정 기능 추가와 몇몇 리팩토링 진행

---

src/app/find-account/panel/SendEmailForm.tsx
src/app/login/page.tsx
src/app/login/panel/OauthLoginBox.tsx
src/app/privacy/page.tsx
src/app/recruit/[id]/page.tsx
src/app/signup/page.tsx

- CuToast의 변경된 props에 맞게 로그인, 회원가입 페이지의 토스트 메시지를 수정했습니다.
- 일부 Typography의 variant 철자문제로 스타일링이 적용되지 않았던 부분을 수정했습니다.

[C-SIGN] 로그인, 회원가입 페이지 CuToast 변경사항에 맞게 수정, 일부 Typography variant수정

---

src/app/about/@contact/page.tsx
src/app/about/@dictionary/page.tsx
src/app/about/@mind/page.tsx
src/app/about/@notice/page.tsx
src/app/about/@peer/page.tsx
src/app/about/@personal/page.tsx
src/app/about/@service/page.tsx
src/app/about/layout.tsx

[ABOUT] about 페이지 뷰 완성

---

src/app/showcase/panel/ShowcaseCard.tsx

[HOTFIX]: 빌드 에러 수정

---

src/app/hitchhiking/panel/CardContainer.style.ts
src/app/hitchhiking/panel/CardContainer.tsx
src/app/hitchhiking/panel/CardStack.tsx
src/app/hitchhiking/panel/HitchhikingCard.style.ts
src/app/hitchhiking/panel/HitchhikingCard.tsx
src/app/hitchhiking/panel/Interest.style.ts
src/app/hitchhiking/panel/Interest.tsx
src/app/hitchhiking/panel/Members.style.ts
src/app/hitchhiking/panel/Members.tsx
src/app/hitchhiking/panel/PostCard.style.ts
src/app/hitchhiking/panel/PostCard.tsx
src/types/IPostCard.ts

1. 히치하이킹 코드파일에서 스타일 코드들을 분리하였습니다.
2. 토스트 메시지를 추가하였습니다.
3. 카드의 너비를 설정하는 부분에서 로직상 오류가 있어 수정하였습니다.
1. 백엔드와 논의해서 모집글 작성자 아이디 받아오기

[H-HITCH] 히치하이킹 스타일 코드 분리 및 토스트 메시지 추가

---

src/app/my-page/homepage-setting/page.tsx
src/app/my-page/homepage-setting/panel/KeywordSetting.tsx
src/app/my-page/homepage-setting/panel/NotifSetting.tsx
src/app/my-page/homepage-setting/panel/TagChip.tsx
src/app/my-page/interests/page.tsx
src/app/my-page/interests/panel/InterestsContents.tsx
src/app/my-page/layout.style.ts
src/app/my-page/layout.tsx
src/app/my-page/loading.tsx
src/app/my-page/privacy/page.tsx
src/app/my-page/privacy/panel/UserInfoEdit.tsx
src/app/my-page/privacy/panel/UserWithdrawalModal.tsx
src/app/panel/main-page/MainCard.tsx
src/components/FavoriteButton.tsx
src/types/IPostDetail.ts

~~# 다음의 PR 머지 이후 리뷰되어야 하는 PR입니다. 리뷰하지 말아주세요!~~ 리뷰 완
https://github.com/peer-42seoul/Peer-Frontend/pull/516
1. 관심리스트에 쇼케이스 리스트를 추가하기 위한 기본 작업을 진행했습니다. 
1. 미리 랜더링하여 Array<ReactNode> 형태로 그리드에 넘기기
- 이렇게 할 경우 상태 변수를 추가하지 않아도 된다는 장점이 있습니다.
2. 쇼케이스를 위한 상태 변수 추가하기
초기에는 1번 방식을 사용하였지만 이후 2번으로 바꾸었습니다. 관심리스트에서 하트를 누를 경우 관심리스트에서 삭제되어야 하는데, 배열 인덱스를 기준으로 하다보니 다른 값이 삭제되는 문제가 있었습니다.
따라서 직접 값에 접근할 수 있도록 기존과 같이 데이터를 상태변수로 관리하록 하였습니다.

[C-MYPAGE] 관심리스트에 쇼케이스 리스트 추가 위한 기본 작업

---

src/app/showcase/page.tsx
src/app/showcase/panel/CardContainer.tsx
src/app/showcase/panel/CardStack.tsx
src/app/showcase/panel/PhoneFrame.tsx
src/app/showcase/panel/ShowcaseCard.tsx
src/app/showcase/panel/ShowcasePc/ShowcasePcLayout.tsx
src/app/showcase/panel/ShowcasePc/ShowcasePcView.tsx
src/app/showcase/panel/types.ts

- 히치하이킹의 모바일 뷰를 차용한 뒤 PC 버전의 뷰을 따로 만들어서 기능을 붙였습니다.
- 기술 스택을 표시하는 칸을 만들었습니다.
- 좋아요와 관심 버튼이 있는데 약간 반응이 느린 점
- 전체 글 보기 리다이렉션
- 테스트 필요

[H-SC] 쇼케이스 PC 버전

---

src/app/recruit/[id]/edit/page.tsx
src/app/recruit/[id]/edit/panel/SetTeamRole/SetTeamRole.tsx
src/app/recruit/write/page.tsx

- 직접 url 접속 방지
- 스터디에서 역할 데이터있으면 글쓰기 안됨
- 역할 삭제 안됨

[J-TB] 모집글 QA 해결 (직접 url 접속 방지, 스터디에서 역할 데이터있으면 글쓰기 안됨, 역할 삭제 안됨)

---

src/app/about/@announce/page.tsx

[BUGFIX] 잘못된 요청 url

---

package-lock.json
package.json
src/api/jwtTocken.ts
src/api/jwtToken.ts
src/components/EncryptedSender.tsx
src/types/EApiType.ts

1. request body값이 변경되면 설정된 api type으로 토큰 요청 및 암호화 진행하여 data에 값을 저장해주는 코드를 작성하였습니다.

[PUBLIC] 민감한 정보 암호화

---

src/app/panel/main-page/MainShowcase.tsx
src/app/showcase/page.tsx
src/app/showcase/panel/PostCard.tsx
src/app/showcase/panel/ShowcasePc/ShowcasePcView.tsx

- 메인 페이지에서 아무런 값이 없을 때 생기는 에러 수정
- 쇼케이스에서 버튼의 응답이 느린 부분

[H-SC] 쇼케이스 메인 페이지 에러 수정 및 쇼케이스 버튼 색상 버그 수정

---

src/app/login/login.style.ts
src/app/login/page.tsx
src/app/signup/page.tsx
src/app/signup/panel/NickNameField.tsx
src/app/signup/panel/PasswordField.tsx
src/app/signup/signup.style.ts
src/components/EncryptedSender.tsx
src/types/EApiType.ts

1. 회원가입 폼 및 로그인 폼에서 보안 처리를 하였습니다.
2. CuToast를 전역 토스트로 바꾸었습니다.
3. 오래된 버그를 고쳤습니다.
close: #319

[B-INFO, C-SIGN] 회원가입 폼 및 로그인 폼 보안 처리

---

src/app/my-page/interests/page.tsx
src/app/my-page/interests/panel/InterestsContents.tsx

- 관심리스트의 변경된 endpoint에 맞게 코드를 hotfix 하였습니다.

[C-MYPAGE] HOTFIX 관심 리스트 end point 변경

---

src/app/showcase/detail/[id]/page.tsx
src/app/showcase/panel/common/TeamName.tsx
src/app/showcase/write/page.tsx

1. 불필요한 Avatar 태그 제거
2. 새로운 예외사항 처리를 추가

refactor : Add error respnose messages

---

src/app/showcase/detail/[id]/page.tsx
src/app/showcase/detail/[id]/panel/CommentContainer.tsx
src/app/showcase/detail/[id]/panel/CommentWriter.tsx
src/types/IComment.ts

- 댓글 기능의 작성, 불러오기 및 삭제를 구현하였습니다.
- 현재 스타일이 인라인 스타일로 다 작성된 상태인데 추후 업데이트에 정리할 예정입니다.

[S-SC] 쇼케이스 내 댓글 기능

---

src/app/showcase/detail/[id]/panel/CommentContainer.style.ts
src/app/showcase/detail/[id]/panel/CommentContainer.tsx
src/app/showcase/detail/[id]/panel/CommentWriter.style.ts
src/app/showcase/detail/[id]/panel/CommentWriter.tsx

- 기존의 인라인 스타일을 모두 style.ts파일로 정리하였습니다.
**작업 이전**
```javascript
<form
onSubmit={submitContent}
style={{
width: '100%',
height: '100%',
display: 'flex',
}}
>
<Stack
style={{
width: '100%',
height: '100%',
display: 'flex',
gap: '1rem',
flexDirection: 'row',
alignItems: 'center',
}}
>
<TextField
type="text"
value={content}
onChange={onChangeContent}
placeholder="댓글을 작성해주세요."
style={{
width: '100%',
height: '100%',
justifyContent: 'center',
color: 'text.alternative',
}}
/>
<IconButton
type="submit"
style={{
width: '1.5rem',
height: '1.5rem',
}}
>
<SendIcon />
</IconButton>
</Stack>
```
**현재**
```javascript
export const containerWrapper = {
width: '100%',
height: 'auto',
}
export const CommentContainer = {
padding: '1.5rem',
borderRadius: '0.75rem 0.7rem 0 0',
backgroundColor: …
```

[S-SC] 쇼케이스 내 댓글 기능 스타일 파일 추가

---

src/app/my-page/homepage-setting/panel/NotifSetting.tsx
src/app/my-page/homepage-setting/panel/TagChip.tsx
src/app/my-page/interests/page.tsx
src/app/my-page/interests/panel/InterestsContents.tsx
src/app/my-page/privacy/panel/PasswordChangeModal.tsx
src/app/my-page/profile/page.tsx
src/app/my-page/profile/panel/MyPortfolio.tsx
src/app/my-page/profile/panel/PostCard.tsx
src/app/my-page/profile/panel/ProfileBioEditor.tsx
src/app/my-page/profile/panel/ProfileLinkEditor.tsx
src/app/my-page/profile/panel/ProfileLinksSection.tsx
src/app/my-page/profile/panel/Skills.tsx
src/app/my-page/profile/panel/SkillsEditor.tsx
src/app/panel/main-page/MainCard.tsx
src/components/BetaBadge.tsx
src/components/CuNavBar.style.ts
src/components/CuNavBar.tsx
src/types/IPostDetail.ts

~~# mypage에서 이전 수정사항이 반영되지 않은 것을 확인하여 수정 중에 있습니다. 리뷰하지 말아주세요!~~ 해결 완
1. 닉네임 변경 이후 로컬스토리지에 최신 닉네임이 반영되지 않는 현상을 수정하였습니다.
2. 관심리스트의 쇼케이스 리스트가 뜨지 않는 버그를 수정하였습니다. 
3. MainCard에 제목과 태그의 최대 길이를 조정할 수 있도록 처리하였습니다.
4. CuNavBar에 디자인 오류 및 다시 클릭 시 선택이 해제되던 오류를 수정하였습니다.
5. 홈페이지 설정의 알림 설정 파트에 beta 벳지를 붙였습니다. 
6. console.log를 모두 지웠습니다.

[PUBLIC, C-MYPAGE] 마이페이지 자잘한 버그 수정 및 CuNavBar 버그 수정 

---

.github/workflows/main.yml
.gitignore

1. 브랜치 체크
2. 브랜치 상태 확인
3. CI
4. CD
총 4개의 단계로 나눠어서 진행합니다.
자세한 설명은 Hoslim에게 주시면 바로 답변 드리겠습니다.

[PUBLIC / ENV] 메인 서버 CI CD 구축

---

src/app/showcase/panel/common/TeamName.style.ts
src/app/showcase/panel/common/TeamName.tsx

[S-SC] 쇼케이스 디테일 폰트 사이즈 수정

---

src/app/my-page/message/@detail/page.tsx
src/app/my-page/message/@detail/panel/MessageForm.tsx
src/app/my-page/message/@list/page.tsx
src/app/my-page/message/@list/panel/MessageBar.style.ts
src/app/my-page/message/@list/panel/MessageBar.tsx
src/app/my-page/message/@list/panel/MessageContainer.tsx
src/app/my-page/message/@list/panel/MobileMessageItem.tsx
src/app/my-page/message/@list/panel/NewMessageForm.tsx
src/app/my-page/message/@list/panel/NewMessageModal.style.ts
src/app/my-page/message/@list/panel/NewMessageModal.tsx
src/hook/useInfiniteScroll.tsx
src/types/TeamBoardTypes.ts

- 기존 Toast 컴포넌트를 사용하고 있어서 알림 메시지가 뜨지 않던 문제를 해결했습니다 (전역 Toast 사용)
- 쪽지 목록, 새 쪽지 보내기 목록에서 검색 버튼에 생기던 줄바꿈을 없앴습니다.
- 쪽지 보내기 요청 뒤에 confirm modal을 닫도록 수정했습니다.
- 불필요해진 NOTE와 TODO 주석을 제거했습니다.
- close #635

[C-MYPAGE] 쪽지 페이지 디자인 버그 수정

---

src/components/ToastUIEditor.tsx

[editor] 에디터 내 이미지 삽입 문제 해결

---

src/app/panel/MuiThemeProvider.tsx
src/app/recruit/[id]/edit/page.tsx
src/app/recruit/write/page.tsx
src/app/recruit/write/panel/CreateTeamEditor.tsx
src/app/recruit/write/panel/fields/BasicSelect.tsx
src/app/recruit/write/panel/fields/SetTeamRole.tsx
src/app/teams/[id]/setting/panel/RedirectRecruitPage.tsx
src/components/CuModal.style.ts
src/components/ImageUploadButton.tsx
src/components/SkillAutocomplete.tsx

1. placeholder들을 변경하였습니다. 
2. 빠진 ui를 구현하였습니다.
3. 모집글 수정을 적용하였습니다.
4. 다음의 버그를 수정하였습니다.
close: https://github.com/peer-42seoul/Peer-Frontend/issues/647

[J-TB] 모집글 작성 페이지 placeholder 변경 및 빠진 ui 구현, 모집글 수정 적용

---

src/app/admin/announce/Announce.tsx
src/app/admin/banner/Banner.tsx
src/app/admin/page.tsx
src/app/admin/panel/AdminAxios.tsx
src/app/admin/tag/Tag.tsx

- REST API 사용시 secure httponly samesite 쿠키를 토큰으로 사용함.
axiosinstance를 위한 커스텀훅으로 중복되는 코드 부분 변경예정

[ADMIN] credential 적용

---

src/app/search/panel/SearchBody.tsx

[BUG/C-SRC] 다른 페이지에서 검색 안되는 버그 수정

---

src/app/teams/[id]/setting/panel/TeamEndProcess/TeamCompleteButton.tsx
src/app/teams/[id]/setting/panel/TeamInfoProcess/SettingTeamStatus.tsx

[BUG / D-TP] 팀 완료 프로세스 에러 수정

---

src/app/panel/PushAlertBanner.tsx
src/app/panel/PwaInstallBanner.tsx

[BUG / PWA] 배너 보이는 방법 로직 교체

---

src/app/find-account/page.tsx
src/app/find-account/panel/SendCodeForm.tsx
src/app/find-account/panel/SendEmailForm.tsx
src/app/login/page.tsx
src/app/login/panel/OauthLoginBox.tsx
src/app/privacy/page.tsx

- 회원가입, 로그인, 비밀번호 찾기의 basebox 스타일이 통합되지 않고 px로 적용되어있던 부분을 수정했습니다.
#703

[C-SIGN] 스타일 변환 및 통일

---

src/app/my-page/profile/panel/Profile.style.ts
src/app/my-page/profile/panel/ProfileBioEditor.tsx
src/app/my-page/profile/panel/ProfileLinkEditor.tsx
src/app/my-page/profile/panel/ProfileLinksSection.tsx
src/types/IUserProfile.ts

1. 닉네임 중복확인 안되는 버그를 수정하였습니다.
2. 기존에 발견한 버그 픽스를 위헤 추가했던 코드를 날렸습니다.
3. 링크 수정이 안되는 버그를 수정하였습니다.
close : #680
close:  #682

[C-MYPAGE] 닉네임 중복확인 안되는 버그 및 링크 수정 안되는 버그 수정

---

src/app/hitchhiking/panel/HitchhikingCard.tsx
src/app/panel/main-page/MainProfile.tsx
src/components/DropdownMenu.tsx

* 원래 드롭다운 버튼 아이콘 방향이 세로였는데, 가로로 바꿨습니다.

[J-TB] 모집글 뷰의 드롭다운 방향 수정

---

src/app/my-page/message/@list/panel/NewMessageModal.tsx
src/app/teams/[id]/board/@list/page.tsx
src/app/teams/[id]/board/@setting/page.tsx
src/app/teams/[id]/board/@setting/panel/BoardItem.tsx

> 브랜치 이름 급하게 만들었더니 한글 들어가있어서 에러가 뜹니다... 무시해주셔도 되는 에러예요!
- #676
- #691
게시판 추가 / 삭제 시 업데이트된 데이터를 바로 받아오지 않는 문제가 있어 mutate를 사용해서 업데이트된 데이터를 바로 받아오도록 수정했습니다.
팀 게시판 관리는 PC에서만 가능하다는 문구를 수정했습니다.
로딩 시에도 에러 피드백을 주도록 되어 있어서 로딩 시 로딩 컴포넌트를 추가했습니다..
이메일로는 검색이 불가능해서 해당 문구 뺐습니다.

[HOTFIX] 팀 게시판 관리 페이지 버그 픽스 + 쪽지 검색 안내문구 수정

---

src/app/my-page/profile/panel/ProfileLinkEditor.tsx
src/app/recruit/[id]/edit/page.tsx
src/app/recruit/write/page.tsx
src/app/recruit/write/panel/CreateTeamEditor.tsx
src/app/recruit/write/panel/fields/Interview/InterviewForm.tsx
src/app/recruit/write/panel/fields/SelectRegion.tsx
src/app/recruit/write/panel/fields/SetTeamRole.tsx
src/components/ControlledTextfield.tsx
src/components/FieldWithLabel.tsx
src/types/IRecruitWriteField.ts

1. 모집글 질문 삭제 확정 후 해당 모달이 꺼지지 않던 문제를 해결하였습니다
2. 모집글 질문 작성 중 백드롭을 누를 시 바로 꺼지던 것을 작성 취소를 하겠느냐는 것으로 바꾸었습니다. 임시 저장으로 처리하길 원한다면 다시 처리하겠습니다.
3. 프론트의 지역 데이터 타입과 백엔드의 지역 데이터 타입이 달라서 발생하던 문제를 해결하였습니다. 
4. 링크 포멧 체크를 추가하였습니다.
5. 커뮤니케이션 링크를 필수 필드에서 제외하였습니다.

[J-TB] 모집글 관련 수정

---

src/app/login/oauth/ft/page.tsx
src/app/login/oauth/google/page.tsx
src/app/login/oauth/page.tsx
src/app/privacy/panel/UsagePolicy.tsx

- 화면 가운데에 CircularProgress와 함께 ~처리 중 문구가 뜨도록 변경했습니다.
resolves: #743 
- 추가로 이용약관 수정중 문구 삭제

[C-SIGN] Oauth 처리 페이지 로딩 컴포넌트 수정

---

src/app/showcase/panel/ShowcaseEditor.tsx
src/app/showcase/panel/common/LinkForm.tsx
src/app/showcase/panel/common/LinksViewer.tsx
src/hook/useLinks.tsx
src/types/IShowcaseEdit.ts

- 동시다발적으로 입력폼이 수정되던 걸 수정하였습니다.
- 링크폼을 삭제할 수 있도록 구현하였습니다.

[BUG] 쇼케이스 수정 폼 링크모음

---

src/app/page.tsx
src/app/panel/MainPage.tsx
src/app/panel/main-page/MainPanel.tsx

* 모바일에서 무한 스크롤 안되는 에러
* SSR 환경에서 메인페이지 리스트가 갱신되지 않는 에러 수정 했습니다.

[C-MAIN] 모바일에서 무한 스크롤 안되는 에러, SSR 환경에서 메인페이지 리스트가 갱신되지 않는 에러 수정

---

src/app/panel/font.ts
styles/global.css

global에 font-family로 적용해서 해결했슴당..!

[HOTFIX] pretendard 적용

---

src/app/recruit/[id]/panel/RecruitQuickMenu.tsx

https://github.com/peer-42seoul/Peer-Frontend/issues/782

[J-TB] 모집글 공유 시 URL 수정

---

src/app/panel/MainPage.tsx
src/app/panel/layout-panel/Header.tsx
src/app/search/panel/SearchBody.tsx

https://github.com/peer-42seoul/Peer-Frontend/issues/735
프로젝트와 스터디가 구분되어 검색될 수 있도록 했습니다.

[BUG / C-SRC] 검색 기능 이슈 수정

---

src/app/recruit/[id]/panel/RecruitQuickMenu.tsx
src/app/showcase/panel/ShowcaseEditor.tsx

- 토스트 에디터에서 고질적인 removeChild() 호출 문제를 box로 감싸서 해결했습니다.

[BUG] 토스트 에디터 removeChild()  문제 해결

---

src/app/layout.tsx
src/app/panel/MuiThemeProvider.tsx
src/app/panel/font.ts
src/constant/ColorTheme.ts
styles/global.css
styles/reset.css

[HOTFIX] 일부 적용 안되던 Pretendard 다시 적용

---

src/app/my-page/message/@detail/page.tsx
src/app/my-page/message/@detail/panel/MessageForm.tsx
src/app/my-page/message/@detail/panel/MessageFormModal.tsx
src/app/my-page/message/@detail/panel/MobileSendButton.tsx
src/app/my-page/message/@list/panel/NewMessageForm.tsx

[C-MYPAGE] 쪽지 버튼 로딩 상태 추가

---

src/app/recruit/[id]/edit/page.tsx
src/app/recruit/write/page.tsx
src/app/recruit/write/panel/CreateTeamEditor.tsx
src/app/recruit/write/panel/fields/Interview/InterviewForm.tsx
src/app/recruit/write/panel/fields/Interview/Options.tsx
src/app/recruit/write/panel/fields/Interview/Question.tsx
src/components/ControlledTextfield.tsx
src/components/FieldWithLabel.tsx
src/components/ToastUIEditor.tsx

1. 모집글 인터뷰 유효성 검사를 추가하였습니다. 
2. 토스트 ui 에디터 가로 길이 처리를 롤백하였습니다.

[J-TB] 모집글 인터뷰 유효성 검사, toast editor width 롤백 등등

---

src/app/hitchhiking/page.tsx
src/app/hitchhiking/panel/CardContainer.tsx
src/app/hitchhiking/panel/Interest.tsx
src/types/IPostCard.ts

[H-HITCH] 히치하이킹 하트 반영 안되는 문제 해결

---

src/app/showcase/panel/ShowcaseEditor.tsx

- payload에 이미지가 null인 경우 전송되지 않는 문제를 수정하였습니다.

[HOTFIX] 쇼케이스 작성 페이로드 수정

---

src/app/admin/announce/Announce.tsx
src/app/admin/banner/Banner.tsx
src/app/admin/login/LoginForm.tsx
src/app/admin/panel/AdminAxios.tsx
src/app/admin/tag/Tag.tsx

- 어드민 공지 글, 배너 글 뷰 화면에서 이미지 업로드액션이 가능한 것 처럼 보인다.
- 불필요한 console.log 제거

[ADMIN] 어드민 공지/배너 글을 볼때 이미지 업로드 버튼 누를 수 있음, 어드민 로그인 엔터로 로그인

---

src/app/panel/MainPage.tsx
src/app/recruit/[id]/panel/RecruitDetailPage.tsx

* 조금 비효율적이지만 useEffect로 맨처음 content의 값을 초기화해줬습니다.
* 추후에 좀 더 좋은 방식으로 개선하고 싶습니다...

[C-MAIN] SSR 로드시 갱신 안되는 문제 수정

---

src/app/admin/tag/Tag.tsx
src/app/admin/tag/panel/NewTag.tsx

[ADMIN] 어드민 태그 관리 페이지 validation 적용

---

src/app/about/@announce/page.tsx
src/app/about/@contact/page.tsx
src/app/panel/main-page/MainCard.style.ts
src/app/panel/main-page/MainCard.tsx
src/app/showcase/panel/CardContainer.tsx

[1.0.2 / ABOUT + C-MAIN] 색상 대비 조정 및 스타일 변경

---

src/app/my-page/profile/panel/Profile.style.ts
src/app/my-page/profile/panel/ProfileCard.tsx
src/app/my-page/profile/panel/ProfileLinkEditor.tsx
src/app/my-page/profile/panel/SkillsEditor.tsx
src/components/SkillAutocomplete.tsx

1. 프로필 이미지가 기본 이미지일 때 이미지 확대 모달에서 오래된 기본 이미지가 나오는 버그를 수정하였습니다.
2. 프로필 링크 수정에서 textfield의 name을 잘못 입력하여 react-hook-form이 제대로 값을 못불러오는 버그를 수정하였습니다.
3. 프로필 스킬 수정에서 모집글 태그 입력 시 버그와는 다른 버그가 일어남을 확인했습니다. 모집글 작성/수정의 버그와 같이 수정하기 위해 모집글 태그 입력에서 사용하는 공통 컴포넌트를 사용하도록 바꾸었습니다.

[C-MYPAGE] 프로필 페이지 버그 수정

---

src/app/page.tsx
src/app/recruit/[id]/edit/page.tsx
src/app/recruit/[id]/page.tsx
src/app/recruit/[id]/panel/RecruitDetailPage.tsx
src/app/recruit/[id]/panel/RecruitQuickMenu.tsx
src/app/showcase/panel/ShowcaseCard.tsx

https://github.com/peer-42seoul/Peer-Frontend/issues/829
* 메인페이지에서 모집글 갱신안되는 에러 수정
* SSR 이슈였습니다.
https://github.com/peer-42seoul/Peer-Frontend/issues/831
* 모집글 수정 시 이전 데이터가 들어가던 오류 수정
* useSWR의 revalidateOnFocus: false 을 제거했습니다.

[C-MAIN] 메인페이지에서 모집글 갱신안되는 에러 수정, 모집글 수정시 이전 데이터가 들어가던 오류 수정

---

src/app/recruit/[id]/edit/page.tsx
src/app/recruit/write/page.tsx
src/app/recruit/write/panel/CreateTeamEditor.tsx
src/app/recruit/write/panel/fields/SetTeamRole.tsx
src/components/SkillAutocomplete.tsx

1. 모집글 역할의 최소글자를 변경하였습니다.
2. 제목 및 팀 이름, 본문의 최대글자를 변경하였습니다.
3. #830 이슈를 해결하기 위해 아스키 코드 중 특수문자를 모두 헥사코드르 변형하였습니다. 관련 근거는 [다음](https://datatracker.ietf.org/doc/html/rfc3986#section-1.1.1)을 참조하여 주세요

[J-TB] 모집글 역할, 제목, 팀이름, 본문 최소 글자, 최대 글자 변경 

---

src/app/panel/MainPage.tsx

https://github.com/peer-42seoul/Peer-Frontend/issues/852
infinite Scroll 오류 수정
- ssr 리패칭 문제를 해결하면서, 기존에 짰던 코드로 롤백했습니다.

[C-MAIN] 무한스크롤 오류 수정

---

src/components/SkillAutocomplete.tsx
src/components/ToastUIEditor.tsx

1. Toast ui editor에서 모바일의 경우 툴바 및 팝업이 잘리는 현상을 수정하였습니다
2. SkillAutocomplete의 코드를 롤백하였습니다.

[PUBLIC] Toast ui editor 모바일에서 툴바 잘림 현상 해결 외 1

---

src/app/hitchhiking/panel/CardContainer.style.ts
src/app/hitchhiking/panel/HitchhikingCard.style.ts
src/app/hitchhiking/panel/HitchhikingCard.tsx
src/app/hitchhiking/panel/PostCard.style.ts
src/components/DropdownMenu.tsx
src/components/ToastUIViewer.tsx
src/types/ToastUI/toastui-editor-viewer.d.ts

1. 모바일에서 좋아요가 보이지 않는 현상을 수정하였습니다 https://github.com/peer-42seoul/Peer-Frontend/issues/844
2. 히치하이킹 뒷면에서 레이아웃이 이상한 문제를 수정하였습니다.
close: #844

[H-HITCH] 히치하이킹 레이아웃 디자인 수정

---

src/app/admin/announce/Announce.tsx
src/app/admin/banner/Banner.tsx

- 24시간 표현됨
- 어드민 공지 에서 날짜 이제 선택할 수 있음

[ADMIN] 어드민 공지에서 날짜 선택이 안됨, 24시간으로 표시가 안됨

---

src/app/my-page/homepage-setting/panel/DisplaySetting.tsx

1. 시스템 모드 사용 유무에 따라 display: none 추가하였습니다.

[C-MYPAGE] 화면 디자인 설정 시스템 모드일 때 다크/라이트 모드 전환 가능한 문제 해결

---

src/app/showcase/panel/common/ImageInput.tsx

hotfix : image size error

---

src/app/recruit/[id]/edit/page.tsx
src/app/recruit/write/panel/CreateTeamEditor.tsx

1. 토스트 에디터가 defaultValue가 있더라도 initValue를 잘못된 것으로 받는 현상 수정하였습니다.

[J-TB] 모집글 수정 시 toast editor에서 initValue를 못받는 현상 수정

---

src/app/showcase/detail/[id]/page.tsx
src/app/showcase/detail/[id]/panel/CommentContainer.tsx
src/app/showcase/detail/[id]/panel/ShowcaseViewer.tsx
src/app/showcase/panel/common/SkillInput.tsx
src/app/showcase/panel/common/StartEndDateViewer.style.ts
src/app/showcase/panel/common/StartEndDateViewer.tsx

[S-SC] 쇼케이스 디테일 디자인 수정

---

src/app/teams/[id]/page.tsx

[1.0.2 / D-TP] 팀 리스트로 돌아가기 버튼 크기 조정

---

src/app/panel/OthersProfile.tsx
src/app/panel/main-page/MainCard.tsx
src/app/teams/[id]/setting/page.tsx
src/app/teams/[id]/setting/panel/RedirectRecruitPage.tsx
src/app/teams/[id]/setting/panel/SettingTeamInfo.tsx
src/app/teams/[id]/setting/panel/TeamEndProcess/TeamCompleteButton.tsx
src/app/teams/[id]/setting/panel/TeamEndProcess/TeamDisperseButton.tsx
src/app/teams/[id]/setting/panel/TeamEndProcess/TeamQuitButton.tsx
src/app/teams/[id]/setting/panel/TeamInfoProcess/SettingTeamActivity.tsx
src/app/teams/[id]/setting/panel/TeamInfoProcess/SettingTeamLocation.tsx
src/app/teams/[id]/setting/panel/TeamInfoProcess/SettingTeamLogo.tsx
src/app/teams/[id]/setting/panel/TeamInfoProcess/SettingTeamName.tsx
src/app/teams/[id]/setting/panel/TeamInfoProcess/SettingTeamStatus.tsx
src/app/teams/[id]/setting/panel/TeamInfoProcess/SettingTeamTime.tsx

- 유령회원 프로필보기 막기
- 팀페이지 디자인 수정
- 모집완료 카드 border색이 라이트모드에서 보이지 않는 문제가 있어 수정
resolves: #869 , #858 , #872

[C-MAIN / D-TP] 유령회원 프로필보기 막기, 팀페이지 디자인 수정 

---

src/app/showcase/detail/[id]/panel/CommentContainer.tsx
src/app/showcase/detail/[id]/panel/ShowcaseViewer.tsx
src/components/CuPhotoBox.tsx
src/types/IComment.ts

아래와 같이 활용하시면 됩니다.
```javascript
// 속성 구조
interface ICuPhotoBoxProps {
style?: React.CSSProperties
src: string
alt: string
}
// 예시
<CuPhotoBox
style={{
position: 'relative',
maxWidth: '100%',
width: '100%',
height: '13.6rem',
margin: 0,
}}
src={image}
alt="이미지"
/>
```

[PUBLIC] NextImage 반응형 공용 컴포넌트 추가

---

src/app/recruit/write/panel/fields/SetTeamRole.tsx
src/components/FieldWithLabel.tsx

1. prepend시 역할의 인원을 기본적으로 1로 설정해서 주던 것을 0으로 통일하였습니다.
2. label을 누르면 내부 버튼이 눌려서 prepend가 되는 현상을 수정하였습니다.
3. 역할을 최대 10개까지만 추가할 수 있도록 처리하였습니다.

[J-TB] 역할 관련 버그 수정

---

src/app/panel/MuiThemeProvider.tsx
src/app/signup/panel/CodeField.tsx
src/app/signup/panel/EmailField.tsx
src/app/signup/panel/NameField.tsx
src/app/signup/panel/NickNameField.tsx
src/app/signup/panel/PasswordField.tsx
src/components/DynamicToastEditor.tsx
src/components/EyeIcon.tsx

- fontSize를 16px로 고치되 scale을 3/4으로 줄여서 기존 디자인을 유지하고 그에 맞춰 다른 width, padding, margin등을 조절했습니다.
close: #903

[C-MAIN, J-TB, ...] 모바일에서 Textfield의 폰트 크기로 인한 auto zoom 현상 막기

---

src/app/panel/main-page/MainBanner.tsx
src/app/panel/main-page/MainCard.tsx
src/app/panel/main-page/MainShowcase.tsx
src/components/CuPhotoBox.tsx
src/components/ToastUIEditor.tsx

*** 수정사항
- 메인 페이지에 next image 태그로 수정하였습니다.

[PUBLIC] 메인 페이지 next image 적용

---

src/app/panel/main-page/MainCard.tsx

전체 카드에 적용된 회색 필터를 좋아요 색상을 위해 사진에만 적용했습니다.

[C-MAIN] 메인 카드에 필터 적용 해제

---

src/app/about/@announce/page.tsx
src/app/about/@contact/page.tsx
src/app/about/layout.tsx
src/app/panel/MuiThemeProvider.tsx

- 멀티라인을 먹일 시 텍스트 필드가 뭉개지는 현상 발생
- 디자인 롤백 이후 색상을 고치는 방향으로 조율 중

[1.0.3 / ABOUT] 가시성 롤백 및 텍스트 필드 스타일 변경

---

src/app/panel/main-page/MainBanner.tsx
src/app/panel/main-page/MainShowcase.tsx
src/components/CuPhotoBox.tsx

- 아래의 이슈에서 발생하던 성능이슈를 유발할 수 있는 에러를 제거했습니다.
https://github.com/peer-42seoul/Peer-Frontend/issues/913

[HOTFIX] Next Image 경고 수정

---

src/app/showcase/detail/[id]/panel/CommentContainer.tsx
src/types/IComment.ts

- 쇼케이스 댓글 작성자 프로파일에 OthersProfile 컴포넌트 적용

update : Add AuthorId in CommentContainer

---

src/app/my-page/homepage-setting/panel/DisplaySetting.tsx
src/app/my-page/homepage-setting/panel/NotifSetting.tsx
src/states/useDarkMode.ts

1. 알림 설정 토글을 누를 시 모달이 켜지도록 처리했습니다.
2. 현재 동의 관련 api가 동작하지 않아 api 관련해서는 주석처리하였습니다. [관련 문서](https://github.com/orgs/peer-42seoul/projects/35/views/1?visibleFields=%5B62310081%2C57249414%2C%22Title%22%2C74457559%2C57248412%2C57314812%2C57248414%2C57248411%2C57315119%2C57315193%2C%22Assignees%22%2C%22Status%22%2C59027629%2C60736503%2C62729696%5D&pane=issue&itemId=52892792)
1. 화면 스타일 설정에서 애니메이션이 제대로 동작하지 않는 현상을 수정하였습니다.

[C-MYPAGE] 알림 설정 api 연결 데모

---

src/app/recruit/[id]/page.tsx
src/app/recruit/[id]/panel/RecruitDetailPage.tsx
src/app/recruit/[id]/panel/RecruitQuickMenu.tsx

- close #925 
1. 모집글 삭제 api에 디테일한 에러 응답 처리 추가
2. 모집글 상세 데이터가 실제로 undefined일 때 타입에러가 발생해서 data prop을 optional하게 수정했습니다.

[1.0.3 / J-TB] 모집글 삭제 기능 보완

---

src/app/teams/[id]/setting/page.tsx
src/app/teams/[id]/setting/panel/ApplicantList.tsx
src/app/teams/[id]/setting/panel/SettingTeamMember.tsx

과거의 게으름을 참회하며 좀 더 세련된 로직으로 교체합니다.

[1.0.3 / I-TM] 새로고침을 이용한 로직을 다른 로직으로 바꾸는 작업

---

src/app/recruit/[id]/panel/RecruitInfoElement.tsx

모집글 뷰의 이미지를 next image로 변경 했습니다

[J-TB] 모집글 뷰의 이미지를 next image로 변경

---

src/app/teams/[id]/showcase/page.tsx
src/app/teams/[id]/showcase/panel/IntersectionSection.tsx

[S-SC] 쇼케이스 삭제 예외처리

---

public/images/iPhoneMock.svg

[1.0.3 / H-SC] 쇼케이스 휴대폰 이미지 변경

---

package-lock.json
src/app/hitchhiking/panel/CardStack.tsx
src/app/showcase/panel/CardStack.tsx

1. 카드를 넘길지 말지 판단할 때, 위-아래만 판단하도록 처리하였습니다
2. 카드를 조금만 당겨도 넘어가도록 처리하였습니다.

[H-HITCH, S-SC] 히치하이킹, 쇼케이스 ux 개선

---

src/app/my-page/message/@detail/panel/MessageItem.style.ts
src/app/my-page/message/@detail/panel/MessageItem.tsx

- close #984 
work-break 속성을 추가해주었습니다.

[1.0.3 / C-MYPAGE] 쪽지 상세페이지 말풍선 줄바꿈 버그

---

src/app/hitchhiking/page.tsx
src/app/hitchhiking/panel/CardContainer.tsx
src/app/hitchhiking/panel/CardStack.tsx
src/app/showcase/page.tsx
src/app/showcase/panel/CardContainer.tsx
src/app/showcase/panel/CardStack.tsx
src/app/showcase/panel/types.ts

쇼케이스 모바일, 히치하이킹에서 카드를 아래로 드래그 할 시 직전 카드가 되돌아오도록 처리하였습니다.

[H-HITCH, S-SC] 히치하이킹, 쇼케이스 아래로 드래그시 되돌리기 기능 추가

---

src/app/team-list/panel/TeamCard.tsx

[I-TM] 팀카드 클릭시 모집글로 이동하는 경우 URL 수정

---

src/app/hitchhiking/page.tsx
src/app/hitchhiking/panel/CardContainer.tsx
src/app/hitchhiking/panel/HitchhikingCard.tsx
src/app/showcase/page.tsx

1. 히치하이킹, 쇼케이스에서 마지막 카드는 없애지 못하도록 처리하였습니다.

[H-HITCH, S-SC] 히치하이킹, 쇼케이스 마지막 카드는 없애지 못하도록 처리

---

src/app/showcase/panel/ShowcaseCard.tsx
src/app/showcase/panel/ShowcasePc/ShowcasePcView.tsx

Refact: Changed showcase to use CuAvatar not Avatar

[S-SC] 쇼케이스에서 CuAvatar 쓰도록 처리 

---

src/app/my-page/message/@list/page.tsx
src/app/panel/main-page/FloatEditButton.tsx
src/components/CuButton.tsx
src/components/CuModal.style.ts

- contained button 내부 텍스트 색상 수정했습니다.

[1.0.3 / style] contained button 내부 텍스트 색상 수정

---

src/app/panel/MainPage.tsx

메인 페이지에 모집글이 없을 시 배너가 작아지는 현상 수정

[C-MAIN] 메인 페이지에 모집글이 없을 시 배너가 작아지는 현상 수정

---

src/components/CuAvatar.tsx
src/components/CuPhotoBox.tsx

1. next image 컴포넌트에 폴백 이미지를 추가하였습니다.

[PUBLIC] next/image 폴백 이미지 추가

---

src/app/my-page/interests/page.tsx

1. 관심리스트에서 에러메시지를 보일 때 박스의 height이 다른 문제를 해결하였습니다.

[C-MYPAGE] 마이페이지 관심 리스트 에러 메세지 minHeight 추가

---

src/app/admin/announce/Announce.tsx

[1.0.4 / admin] 어드민 공지 뷰에서 토스트에디터뷰어와 작성시간이 안보이는 문제 해결

---

src/app/teams/[id]/setting/page.tsx
src/app/teams/[id]/setting/panel/ApplicantList.tsx
src/app/teams/[id]/setting/panel/TeamInfoProcess/SettingTeamLogo.tsx

기존에 피어 로그를 넣었던 게 헷갈린다는 피드백이 있습니다.

[1.0.5 / I-TM] 팀 설정 페이지 팀 로고에 디자인 반영

---

src/app/showcase/detail/[id]/panel/CommentContainer.style.ts
src/app/showcase/detail/[id]/panel/CommentContainer.tsx
src/app/showcase/detail/[id]/panel/CommentWriter.tsx

- close #1028 
1. 댓글 수정 기능을 추가하였습니다.

[1.0.7 / S-SC] 쇼케이스 내 댓글 수정 기능 추가

---

src/app/recruit/[id]/panel/RecruitContentText.tsx
src/app/showcase/detail/[id]/panel/CommentContainer.tsx
src/app/showcase/panel/common/LinksViewer.tsx
src/app/showcase/panel/common/StartEndDateViewer.tsx
src/app/showcase/panel/common/TeamMembers.tsx
src/components/LabelWithIcon.tsx
src/components/board/CommentPanel.tsx
src/components/board/DetailPanel.tsx
styles/global.css

- close #1049
글씨가 작다는 피드백을 받은 페이지들의 폰트 크기를 1단계씩 올렸습니다.
전 / 후
- (제목) Caption -> Body2
- (내용) Body2 -> Body1
전 / 후
- (제목) CaptionEmphasis -> Body2Emphasis
- (내용) Body2 -> Body1
전 / 후
- (작성자 닉네임) Caption -> Body2
- (댓글 내용) Body2 -> Body1
- (작성 시간) Tag -> Caption
전 / 후
- (내용) Body2 -> Body1
- (제목) CaptionEmphasis -> Body2Emphasis
- (작성자 닉네임) Caption -> Body2
- (댓글 내용) Body2 -> Body1
- (작성 시간) Tag -> Caption
각 태그의 값은 https://mui.com/material-ui/customization/default-theme/?expand-path=$.typography 참고해서 지정했습니다..

[1.0.7 / DESIGN] 폰트 크기 조정

---

src/app/recruit/[id]/panel/RecruitContentText.tsx
src/app/showcase/detail/[id]/panel/CommentContainer.tsx
src/app/showcase/panel/common/LinksViewer.tsx
src/app/showcase/panel/common/StartEndDateViewer.tsx
src/app/showcase/panel/common/TeamMembers.tsx
src/components/LabelWithIcon.tsx
src/components/board/CommentPanel.tsx
src/components/board/DetailPanel.tsx
styles/global.css

Reverts peer-42seoul/Peer-Frontend#1099
main으로 잘못 merge된 PR을 release-1.0.7로 다시 올리기 위해 되돌립니다.

Revert "[1.0.7 / DESIGN] 폰트 크기 조정"

---

src/app/recruit/[id]/panel/RecruitDetailContent.tsx
src/app/recruit/[id]/panel/RecruitInfo.tsx

[1.0.7/J-TB] 모집글 뷰 팀명<->닉네임 위치 변경

---

src/app/recruit/[id]/page.tsx
src/components/NextSeo.tsx

모집글 뷰 페이지의 동적 메타 데이터를 추가했습니다.
이제 공유 시에 해당 게시글의 내용이 공유됩니다.
https://github.com/peer-42seoul/Peer-Frontend/issues/1122

[J-TB] 동적 메타데이터 추가

---

package-lock.json
package.json
src/app/recruit/write/page.tsx
src/utils/createGithubIssue.ts

- close #1130
슬랙 알림을 위한 깃허브 이슈 등록 기능 임시로 추가했습니다. 
내용 피드백 부탁드립니다...ㅎㅎ
환경변수 추가해주세요!
```
NEXT_PUBLIC_GITHUB_TOKEN="본인 깃허브 토큰"
```

[J-TB] 깃허브 이슈 등록 기능

---

src/app/job/[id]/page.tsx
src/app/job/layout.tsx
src/app/job/template.tsx
src/components/HitsCounter.tsx

- http://localhost:3000/job/1 에서 테스트데이터 확인할 수 있습니다!
- 채용 공고 게시판 상세 페이지
- 수정, 삭제, 댓글 기능 없이 게시글을 확인하는 기능만 있는 페이지입니다~

채용 공고 게시물 상세 페이지

---

src/app/job/JobCard.tsx
src/app/job/page.tsx
src/app/panel/layout-panel/Header.tsx
src/app/panel/layout-panel/MobileNav.tsx
src/app/panel/layout-panel/PcNav.tsx
src/types/IJob.tsx

* 목록 페이지
* 네비게이션바의 쇼케이스를 채용공고로 수정했습니다.

채용 공고 목록 페이지

---

src/app/panel/layout-panel/MobileNav.tsx
src/app/panel/layout-panel/PcNav.tsx
src/components/board/DetailPanel.tsx
src/utils/createGithubIssue.ts

1.0.9 버전 릴리즈 과정에서 발견된 빌드 에러를 수정했습니다. (job 과 관련된 타입 선언 추가)

[FIX] 빌드 에러 수정

---

src/utils/createGithubIssue.ts

resolves #1144
테스트용 토큰 출력 코드를 삭제합니다.
--
기능 변경이 없고 빠르게 배포하기 위해 리뷰 생략하겠습니다..

[FIX] 테스트 코드 제거
