peer_web_frontend/src/app/signup/page.tsx
회원가입 페이지에서 이메일, 패스워드, 닉네임 등 입력을 받는 FormField 컴포넌트를 만들어봤습니다. 
이메일 인증로직을 짜는 중인데, use-hook-form의 Controller 컴포넌트에서 렌더링되는 TextField값을 
어떻게 알아올 수 있는지 확인 중에 있어서 막혀있는 상태인데, 
현재는 이메일 인증 버튼을 클릭하면, 인증코드가 전송되었습니다. 
라는 문구만 렌더링하고 있습니다.
막혀있는 부분 빨리 해결하고 로직 더 작성해보겠습니다!!
=> [B-INFO] 회원가입 페이지에서 입력필드 추상화 및 이메일 인증 로직 작성중

peer_web_frontend/src/app/profile/MyPage/page.tsx, peer_web_frontend/src/app/profile/MyPage/panel/ProfileCard.tsx, peer_web_frontend/src/app/profile/MyPage/panel/ProfileLinksSection.tsx, peer_web_frontend/src/app/profile/MyPage/panel/ProfileSection.tsx, peer_web_frontend/src/types/IUserProfile.ts
1. 링크에 대한 제목을 유저가 넣을 수 있도록 링크 리스트의 타입이 바뀌었습니다. 
2. ProfileSection이라는 컴포넌트로 프로필 페이지의 section을 구분해주었습니다.
3. profile page의 ui에 링크 모듈 컴포넌트를 추가하였습니다.
1. ProfileSection에 sectionTitle을 넣도록 변경하였습니다. 그렇게 한 이유는 이후 편집으로 넘어갔을 때 라우팅 처리를 위해서 입니다.
=> [C-MYPAGE-20,21,23] 링크 모듈 UI 변경

peer_web_frontend/src/app/find-account/page.tsx, peer_web_frontend/src/app/find-account/panel/SendCodeForm.tsx, peer_web_frontend/src/app/find-account/panel/SendEmailForm.tsx
비밀번호 찾기 과정이 임시비밀번호 발급으로 바뀜에 따라 코드 인증 후 로그인 페이지로 이동하는 로직으로 다시 작성했습니다.
추가로 인증코드 메일을 전송하면 유효시간(5분)을 설정해 사용자에게 타이머가 보여지고, 유효시간이 지나면 페이지를 새로고침하도록 했습니다.
=> [C-SIGN-03] 비밀번호 찾기 페이지 수정

peer_web_frontend/src/app/profile/MyPage/page.tsx, peer_web_frontend/src/app/profile/MyPage/panel/ProfileBioEditor.tsx, peer_web_frontend/src/components/CuTextField.tsx
1. 닉네임이 빈칸일 경우 띄워주는 placeholder를 추가하였습니다.
2. 닉네임 인풋박스와 자기소개 인풋 박스에 쓸 수 있는 최대 글자 수를 제한하였습니다.
- CuTextField
1. placeholder가 추가되었습니다. 
- 필수 작성란일 경우 해당사항을 알려주기 위함입니다.
2. inputProps가 추가되었습니다.
- pattern이나 maxLength등등을 넣기 위함입니다.
=> [C-MYPAGE] 소개 파트 수정 모달 추가 구현

peer_web_frontend/src/app/layout.tsx, peer_web_frontend/src/app/panel/MuiThemeProvider.tsx, peer_web_frontend/src/app/profile/MyPage/layout.tsx, peer_web_frontend/src/app/profile/MyPage/page.tsx, peer_web_frontend/src/app/profile/MyPage/panel/SubNavBar.tsx
1. 마이페이지 pc뷰의 서브 네비게이션 바를 추가하였습니다.
2. sm prop이 480 이상일 때 작동하도록 테마를 커스터마이징 해주었습니다.
=> [PUBLIC & C-MYPAGE] pc뷰 서브 네비게이션 바 및 모바일 pc 구분 위한 theme설정

peer_web_frontend/src/app/search/panel/SearchBody.tsx
기존 검색창에서 api를 사용해서 검색 데이터를 불러오는 구조에서 메인에 키워드를 전달하고 메인에서 다시 api를 사용하는 걸로 변경
=> [C-SRC] 검색 로직 변경

peer_web_frontend/src/app/profile/MyPage/page.tsx, peer_web_frontend/src/app/profile/MyPage/panel/ProfileBioEditor.tsx, peer_web_frontend/src/app/profile/MyPage/panel/ProfileLinkEditor.tsx, peer_web_frontend/src/app/profile/MyPage/panel/SettingContainer.tsx, peer_web_frontend/src/components/CuToast.tsx, peer_web_frontend/src/hook/useToast.tsx, peer_web_frontend/src/types/IUserProfile.ts
1. 공통 toast 컴포넌트를 구현하였습니다.
2. mui의 예시코드를 활용하였으며, severity를 'error'로 사용하면 뜨는 ui는 다음과 같습니다.
1. mui의 예시코드를 활용하였습니다.
2. isOpen, openToast, closeToast, CuToast를 리턴합니다.
1. form submit시 문제가 있을 경우 toast를 띄우도록 처리했습니다.
=> [PUBLIC & C-MYPAGE] 공통 토스트 컴포넌트 useToast 구현 및 링크 수정 에러 헨들링

peer_web_frontend/src/app/signup/hook/useSignUpForm.ts, peer_web_frontend/src/app/signup/panel/SignUpField.tsx
제어되지 않는 컴포넌트 변환 에러 해결
- 텍스트 필드 value가 초기에 undefine로 되는데 입력이 들어오면 value가 정의됩니다. 
이때 콘솔에 제어되지 않는 컴포넌트를 제어된 컴포넌트로 변경한다는 에러(A component is changing an uncontrolled input to be controlled)가 발생하는데, undefine일 때 빈 문자열로 넣어준다는 코드를 넣었을 때 해결되었습니다.
=> [B-INFO] 콘솔 에러 수정

src/app/teams/@main/[id]/page.tsx, src/app/teams/@main/[id]/panel/TeamInfoComponent.tsx, src/app/teams/@main/[id]/panel/TeamInfoContainer.tsx, src/app/teams/@main/[id]/panel/TeamMemberModal.tsx, src/types/ITeamInfo.ts
`/teams/[id]` 페이지 중 DnD를 제외한 부분을 추가했습니다.
- 받아온 팀 정보를 확인할 수 있습니다. (와이어프레임이 아직 확정되지 않아서 임의로 적용해두었습니다.)
- 팀원 수 정보를 눌러서 참여 중인 팀원의 정보 모달을 띄울 수 있습니다.
- api 요청을 확인해볼수가 없어서 mock data로 적용해두었습니다.
- 와이어프레임 확정되면 컴포넌트 배치하기
- api 연동하기
=> [D-TP-21~30, 39, 41] 팀 페이지 - 메인 페이지 추가

src/app/signup/page.tsx, src/app/signup/panel/CodeField.tsx, src/app/signup/panel/CodeTimer.tsx, src/app/signup/panel/EmailField.tsx
- 닉네임 필드 validation 추가했습니다.
- 닉네임 한글, 영문, 숫자만 사용가능하게 했습니다.
- 이메일 필드, 전송코드 필드가 제출되고 나서는 입력을 수정하지 못하게 막았습니다.
- toast UI 적용시켰습니다.
=> [B-INFO] 인증코드 타이머 추가

src/app/signup/page.tsx, src/app/signup/panel/CodeField.tsx
- 텍스트 필드 최대 입력값을 10으로 바꿔서 인증코드 에러 문제를 해결했습니다.
- 회원가입 폼 제출할 때 유효하지 않다고 나오는데 이거는 해결을 못했습니다. 일단 콘솔로 찍어봤을 때 문제가 없어 보입니다.
=> [B-INFO] 회원가입 인증코드 에러 수정

src/app/privacy/page.tsx
- 와이어프레임 디자인 반영 (회원가입 디자인과 동일)
- 체크박스 로직 반영
- 다음을 누르면 signup 페이지로 리디렉션
- login 페이지에서 회원가입 버튼 누를시 privcay 페이지로 리디렉션작업이 필요함 지금은 privacy를 거치지 않고 회원가입페이지로 넘어감.
@KRimwoo
=> [A-JOI] 개인정보동의서명 와이어프레임반영 및 체크박스로직, route 추가

src/api/config.ts, src/app/find-account/panel/SendCodeForm.tsx, src/app/find-account/panel/SendEmailForm.tsx
- 백에서 요구하는 데이터 형식과 주소에 맞추어 코드를 다시 수정하고 연동이 잘 되는지 테스트까지 해보았습니다.
- 다만, 이메일로 받는 임시비밀번호 자체에는 아직 문제가 있는 상황이라 임시비밀번호로 로그인까지는 불가능한 상황입니다
=> [C-SIGN] find-account 페이지의 api 연동 오류 수정 + interceptor reissue 오류 수정

src/app/my-page/privacy/panel/EyeIcon.tsx, src/app/my-page/privacy/panel/UserInfoEdit.tsx
- 비밀번호 변경 API에 맞게 수정했습니다.
- 패스워드를 볼 수 있게 눈모양 아이콘을 넣었습니다.
- 패스워드 검증 로직을 회원가입하고 맞췄습니다.
- 비밀번호를 바꾸고 난 후 필드를 리셋시켰습니다.
=> [C-MYPAGE-11] 개인정보 페이지에서 비밀번호 변경 API 수정

src/app/my-page/interests/page.tsx, src/app/page.tsx, src/app/panel/MainCard.tsx, src/app/panel/MainPage.tsx, src/app/panel/MainProfile.tsx, src/app/panel/Options.tsx, src/app/recruitment/[id]/page.tsx, src/app/recruitment/[id]/panel/RecruitFormModal.tsx, src/app/recruitment/[id]/panel/RecruitFormText.tsx, src/app/teams/@setting/[id]/panel/SetupSelect.tsx, src/types/IPagination.ts, src/types/IPostDetail.ts
**어제 api 연동에 성공했고, 이에 따라 생기는 여러 문제를 해결했습니다.** 
- 변수명을 백엔드의 dto에 따라 수정했습니다
- 요청 url도 일부수정했습니다.
- 메인페이지의 카드 컴포넌트의 관심글 기능과 이동 기능이 같이 작동할 수 있도록 하기 위해, Link가 감싸고있는 범위를 쪼갰습니다. (관심글 기능은 LInk가 적용되지 않도록)
- 세부옵션의 경우, 가능한 작업스택 목록을 불러오는 TagData api가 새로 생겨 적용했습니다.
- 통일성을 위해, 세부옵션에서 목표 기간 선택 부분을 팀 페이지에서 사용하는 SetupSelect 컴포넌트로 일단 대체했습니다 (추후 변경 사항이 있으면 같이 수정하겠습니다)
- IPagination라는 interface를 만들었습니다. 백엔드에서 pagination을 이용해 가져오는 data의 인터페이스입니다
**아직 완벽하게 세부 옵션 검색이 작동하지는 않습니다. 이 부분 백엔드와 확인 후 다시 수정될 예정입니다
참고 이슈
https://github.com/peer-42seoul/Peer-Frontend/issues/243
https://github.com/peer-42seoul/Peer-Frontend/issues/202
=> [C-MAIN][J-TB] 메인페이지, 모집글 뷰페이지의 API 연동에 따른 변수수정 + 세부옵션 수정

src/app/privacy/page.tsx
- Oauth 회원가입 시에도 개인정보 동의가 필요해서 백엔드에서 오는 url이 개인정보 동의란 페이지로 변경되었습니다.
- Oauth 정보가 쿼리 스트링으로 넘어오는데 회원가입 페이지에서 이게 필요해서 개인정보 동의란 페이지에서 Oauth 회원가입페이지로 쿼리 스트링을 넘겨주는 로직을 작성했습니다.
=> [A-JOI] Oauth 회원가입 시 개인정보 동의란으로 이동

src/app/my-page/privacy/panel/UserInfoEdit.tsx
- #300 validation 검사에서 대문자를 검증을 못해줘서 패스워드 모든 속성을 각각 따로 유효성 검사 진행하는 로직으로 바꿨습니다.
=> [FIX] 비밀번호 변경 시 대문자 유효성 검사 에러

src/app/my-page/privacy/panel/UserWithdrawalModal.tsx, src/app/privacy/page.tsx, src/app/signup/page.tsx
-  #292 로그인 상태에서 회원가입 페이지로 진입하지 못하게 했습니다.
- #294 회원 탈퇴 시 전역 상태에서 로그인 상태가 지속됐는데 전역 상태에서 로그인 토큰를 null로 isLogin 변수를 false로 초기화 시켰습니다.
=> [FIX] 로그인 상태에서 회원가입 접근 막기 및 회원 탈퇴 후 Zustand Login 상태 초기화

src/app/my-page/privacy/panel/UserInfoEdit.tsx, src/app/my-page/privacy/panel/UserWithdrawalModal.tsx
- autoComplete로 인해 비밀번호 변경을 누르지 않았는데도 강력한 비밀번호 추천 만으로도 '비밀번호를 업데이트 하시겠습니까' 라는 모달이 나옵니다.
- autoComplete 값을 off로 변경했습니다.
=> [HOTFIX] autoComplete Prop off로 변경

src/app/my-page/message/panel/MessageBar.tsx, src/app/my-page/message/panel/MessageContainer.tsx, src/app/my-page/message/panel/MessageList.tsx, src/hook/useSelectCheckbox.tsx
- SearchBar 컴포넌트와 ManageBar 컴포넌트를 my-page/message/panel/MessageBar.tsx 파일로 뺐습니다.
- 체크박스 전체 선택 / 전체 해제 / 체크 OR 체크 해제 / 모두 선택 여부 확인 기능을 처리하는 useSelectCheckBox 훅을 만들었습니다.
- 전체 선택 / 전체 선택 해제 버튼을 눌렀을 때 체크박스에 표시되도록 수정했습니다. (체크박스의 check property를 직접 지정해줌)
상위 컴포넌트에서 하위 컴포넌트로 내려줘야 하는 내용들이 많아서 전반적으로 컴포넌트들에 props가 너무 많은데 괜찮은 구조인지 잘 모르겠습니다...
=> [C-MYPAGE] 쪽지 전체 선택 / 해제 기능 추가

src/app/my-page/message/[id]/page.tsx, src/app/my-page/message/[id]/panel/MessageForm.tsx, src/app/my-page/message/panel/MessageBar.tsx, src/app/my-page/message/panel/MessageContainer.tsx, src/types/IMessage.ts
close #302
- (api 수정) 쪽지 target 객체에 deleted 값 추가. 상대가 삭제한 경우에는 메시지를 보낼 수 없게 입력창과 버튼을 비활성화했습니다. (테스트 완료 ✅)
- (api 수정) 쪽지 답장 시 410 에러가 오면 상대가 쪽지를 삭제한 경우이므로 입력창과 버튼을 비활성화했습니다. (테스트 전)
- (api 수정) 랜더링 순서에 맞게 쪽지 배열을 뒤집어서 보여주던 부분을 서버에서부터 뒤집어서 보여주도록 변경하여 배열을 뒤집는 로직을 삭제했습니다. (테스트 완료 ✅)
- 쪽지를 성공적으로 보낸 뒤의 alert 제거
- 쪽지 목록 관리 모드에서 관리모드를 빠져나가기 위한 버튼 추가
=> [C-MYPAGE] 쪽지 삭제 기능 개선사항 및 자잘한 개선사항 반영

src/api/config.ts
무한 요청을 막기위해 isRefreshing flag를 설정했었는데, isRefreshing=true를 선언하는 시점이 잘못되어있어서 reissue를 요청하는 구문이 실행되지 않았던 문제를 해결했습니다.
=> [C-SIGN] isRefreshing 설정 시점 수정

src/app/my-page/message/[id]/panel/MessageForm.tsx
close #389 
PC 화면에서는 전송 버튼 뿐 아니라 엔터를 눌러서도 쪽지를 보낼 수 있었어야 했는데 그 부분이 누락되었었습니다...
submit 기능이 있어서 form 태그가 어울리는데 적용이 안되어있었어서 form 태그를 적용하면서 위의 문제도 같이 해결했습니다.
=> [C-MYPAGE] 쪽지 보내기 기능 누락 수정

src/app/my-page/profile/panel/ProfileBioEditor.tsx, src/app/my-page/profile/panel/ProfileCard.tsx, src/app/my-page/profile/panel/ProfileLinksSection.tsx, src/app/panel/layout-panel/NavBar.tsx
1. 히치하이킹에 대한 라우팅을 추가하였습니다.
2. 마이페이지의 next image 컴포넌트를 mui box로 변경하였습니다.
3. 마이페이지의 링크를 누르면 peer-test/www.mylink.com과 같이 사이트 도메인이 붙던 현상을 수정하였습니다.
- 우선은 프로토콜이 없으면 '//'를 붙여 해당 링크가 도메인이 루트임을 알려주었으나 몇몇 sns 테스트 시 프로토콜을 명시하지 않으면 일단 'http://'를 붙여서 저장하고 있어 고민이 필요할 것 같습니다.
- 참고 링크 : [Href without http(s) prefix](https://stackoverflow.com/questions/43803778/href-without-https-prefix)
4. 크롭 박스가 움직이던 현상을 수정하였습니다.
=> [C-MYPAGE] 마이페이지 Next Image 컴포넌트 mui box로 변경

src/app/panel/layout-panel/NavBar.tsx, src/app/recruit/[id]/panel/ApplyButton.tsx, src/app/recruit/[id]/panel/LinkButton.style.ts, src/app/recruit/[id]/panel/LinkButton.tsx
수정 전
수정 후
- 모집글 버튼의 z-index를 제거하기 위해서, 링크 버튼에 적용되어 있던 Popover를 Tooltip으로 수정했습니다.
- Popover와 비슷한 Popper를 사용하려고 했었으나, 단순히 마우스 호버 시에 링크 정보만 보여주는 것이므로 Tooltip이 더 알맞겠다 생각했어요.
- https://mui.com/material-ui/react-tooltip/
- 기존에도 padding 외에 특별히 디자인이 적용되어 있지 않았어서 이번에도 padding 외에는 디자인을 추가하지 않았습니다.
- 헤더와 네비게이션 바에 적용한 z-index를 좀 낮춰주려고 했었는데, 어떤 값으로 설정해야 할지 잘 모르겠어서 그대로 두고 주석만 수정해두었습니다.
- close #418
=> [DESIGN] 모집글 버튼 z-index 조정

src/app/my-page/homepage-setting/page.tsx, src/app/my-page/homepage-setting/panel/KeywordSetting.tsx, src/components/CuToast.tsx
1. 다크모드에서 x가 잘 보이지 않는다는 지적이 있어 색을 변경하였습니다. 보고 더 밝은 색으로 바꿔야 할 것 같으면 말씀해주세요.
2. message prop의 타입을 React.Node로 변경하였습니다. 이는 중간에 `<b>` 태그 등의 인라인 태그를 넣기 위함입니다.
=> [PUBLIC] CuToast 디자인 변경 및 message prop 타입 변경

src/app/showcase/[id]/panel/ShowcaseViewer.tsx, src/app/showcase/panel/ShowcaseEditor.tsx, src/app/showcase/panel/common/LinksViewer.tsx, src/app/teams/[id]/showcase/page.tsx, src/app/teams/[id]/showcase/panel/ContentSection.tsx, src/app/teams/[id]/showcase/panel/CreateShowcasePage.tsx, src/app/teams/[id]/showcase/panel/IntersectionSection.tsx, src/types/IShowcaseEdit.ts
- 팀페이지에서 쇼케이스 탭 부분 레이아웃 구현
- 스타일 적용
- 백엔드 api 연동
=> [S-SC] 쇼케이스 리다이렉션 페이지 구현

src/components/ImageUploadButton.tsx
이미지 업로드시 이미지 4mb 용량 업로드 제한 적용이 완료되었습니다.
아래와 같이 alert로 막아버림.
해당 사진
=> [J-TB] 모집글 작성/수정 QA 이미지 4mb 용량 업로드 제한 적용

src/app/showcase/panel/ShowcaseEditor.tsx, src/app/showcase/panel/common/FormUIEditor.tsx, src/app/showcase/panel/common/ImageInput.tsx, src/states/useShowCaseState.tsx
1. ShocaseEditor.tsx 에서 컨텐츠에 새로 수정된 사항이 없으면 content 데이터를 null 로 입력하여 초기화 하던 현상을 수정했습니다.
```js
// 추가된 코드
// 기존에는 setContent에 아무런 값을 불러오지 않아서 수정하면 컨텐츠가 사라지는 현상이 있었습니다.
useEffect(() => {
if (requestMethodType === 'put') {
setContent(data?.content)
}
}, [requestMethodType, data?.content])
```
2. put 요청 시 대표 이미지가 수정되지 않으면 image가 put 되지 않던 사항을 수정하였습니다.
```js
// 추가된 코드
// image 객체에 새로 수정된 값이 없을 경우엔 이미지를 null로 보냅니다.
await axiosWithAuth.put(
`${process.env.NEXT_PUBLIC_API_URL}/api/v1/showcase/edit/${teamId}`,
{
image: image.length ? previewImage.split(',')[1] : null,
content: content,
links: linksWithoutId,
},
)
```
=> [S-SC] 쇼케이스 수정폼 에러 수정

src/app/privacy/page.tsx, src/app/privacy/panel/PrivacyPolicy.tsx, src/app/signup/page.tsx
1. 회원 가입 시 규정 동의 시간을 회원가입 폼에 추가하였습니다.
2. 전체 동의 버튼에 부모 체크 박스라는 맥락이 없어 추가하였습니다.
3. 개인 정보 활용 정책 컴포넌트를 만들었습니다. (개인적으로 다른 파일을 만들어 그 파일을 읽어오도록 하고 싶었지만 구현상의 한계로 그러지 못하였습니다.)
4. 동의 하지 않은 채 signup 페이지로 넘어갈 시 메인으로 리다이렉션 시켰습니다.
5. 하류님이랑 잠시 이야기 했는데 링크로 마크다운 데이터로 가져와서 마크다운 뷰어로 보여주는 게 가능하다고 합니다. 앞으로는 그 방식을 사용해야 할 것 같습니다.
=> [B-INFO] 회원 가입 시 규정 동의 값 회원가입 폼에 추가

src/app/panel/MainPage.tsx, src/components/Tutorial.style.ts, src/components/Tutorial.tsx, src/components/tutorialContent/MainPageTutorial.tsx, src/components/tutorialContent/TutorialComponent.tsx
튜토리얼을 띄울 수 있는 버튼과 모달을 추가했습니다.
Tutorial 컴포넌트에 튜토리얼 컨텐츠를 Props로 전달할 수 있게 했고
(튜토리얼 컨텐츠는 페이지에 두는 것 보다 따로 폴더에 모아두는게 좋을 것 같아요 `@/components/tutorialContent/MainPageTutorial`)
일괄적인 디자인을 넣기 편하게 Tutorial Component 들을 추가했습니다.
디자인 적용 확인을 위해서 임시로 메인 페이지 튜토리얼을 추가했습니다.
=> [Public] 튜토리얼 컴포넌트 추가

src/components/ToastUIViewer.tsx, styles/global.css
다크 모드에선 toast-viewer에서 기본적으로 적용하는 폰트 컬러가 시인성이 낮아서, 시스템 환경에 맞는 컬러로 변경하였습니다.
```css
/* 라이트 모드일 때 */
@media (prefers-color-scheme: light) {
.toastui-editor-contents p {
color: #1a1a1a !important;
}
}
/* 다크 모드일 때 */
@media (prefers-color-scheme: dark) {
.toastui-editor-contents p {
color: #f6f6f6 !important;
}
}
```
=> [PUBLIC] 토스트 에디터 뷰어 폰트 컬러 변경 

src/app/recruit/[id]/panel/ApplyDefaultButton.tsx, src/app/recruit/[id]/panel/ApplyDrawerButton.tsx, src/app/recruit/[id]/panel/ApplyFormButton.tsx, src/app/recruit/[id]/panel/ApplyMenuButton.tsx, src/app/recruit/[id]/panel/RecruitDetailPage.tsx, src/app/recruit/[id]/panel/RecruitInfo.tsx, src/app/recruit/[id]/panel/RecruitQuickMenu.tsx, src/components/dropdownMenu/ShareMenuItem.tsx
* 모집글 뷰도 ssr로 렌더링 되기 때문에, 좋아요를 get하는 로직을 따로 추가해주었습니다.
* 지원하기 버튼 위치를 조정했습니다. 
* 모집글에 있던 신고하기 버튼은 없애고 (어차피 유저로 신고할테니까) pc뷰 공유 버튼에 다른 컴포넌트에 있던 공유 기능을 가져와 연결했습니다. 이 과정에서 share function을 기존 컴포넌트에서 분리했는데, 혹시 문제가 있을지 확인부탁드립니다.
* 지원 시 버튼에 몇명 남았는지도 보여주었습니다. (- 역할이 있는 경우에만 넣었는데, 역할없는 스터디에도 필요할까요? 지금 스터디는 드롭다운이 아닌데, 그냥 버튼에 지원하기 옆에 명수를 적어줄지 아니면 그냥 스터디 버튼도 드롭다운으로 바꿀지 고민입니다.)
@todo 
실제로 공유해보면 이런식으로 뜨는데 맞는 작동방식인지 확인해봐야 할 것 같습니다.
=> [J-TB] 좋아요 GET 로직 추가, 레이아웃 수정, 공유 기능 연결

src/app/panel/MainLayout.tsx, src/app/panel/layout-panel/MobileNav.tsx, src/app/panel/layout-panel/PcNav.tsx, src/app/panel/main-page/FloatEditButton.tsx, styles/global.css
* ios의 하단의 safe area에 하단 네비게이션이 겹치지 않도록 네비게이션에 padding을 주었습니다 (대신 safe area가 거의 없는 기기에도 padding이 생겨버렸습니다...)
* env (https://developer.mozilla.org/en-US/docs/Web/CSS/env)를 통해 padding을 조건부로 주고 싶었는데 생각대로 잘 작동하지 않아 임시방편으로 해둔 조치입니다. 추후 더 좋은 방법이 있으면 바꿀 예정입니다.
=> [C-TB] 모바일 네비게이션바 safe area 문제

src/app/teams/[id]/notice/@list/panel/NoticeList.tsx, src/app/teams/[id]/panel/TeamInfoContainer.tsx, src/app/teams/[id]/setting/page.tsx, src/components/board/ListPanel.tsx
팀 페이지 접근 제한 로직을 추가했습니다.
팀 메인 페이지, 공지사항 페이지, 게시판 페이지(는 이미 제한 로직이 추가되어 있었음), 설정 페이지에서
권한이 없거나 에러가 발생한 경우에 alert를 띄우고 팀 리스트 페이지로 이동하도록 했습니다.
- close #485
=> [D-TP] 팀 페이지 접근 제한 로직 추가

src/app/login/forbidden/page.tsx, src/app/login/page.tsx, src/components/EncryptedSender.tsx
- OAuth 로그인 또는 연동 상황에서 정지된 계정, 이미 연결된 계정, oauth 자체 오류 등이 발생하면 백에서 login/forbidden 페이지와 code를 쿼리로 반환합니다. 이에 따라 toast message와 page redirection을 처리했습니다.
=> [C-SIGN] OAuth 로그인, 연동 시 fobidden 페이지로 반환되는 경우 처리

src/components/ToastUIEditor.tsx, src/types/ToastUI/editor.d.ts
- base64 가 그대로 본문내에 삽입되어 백엔드에 전송되던 상황
- base64 이미지파일을 /api/v1/editor/image 엔드포인트로 post 해서 보내면 response로 nhn object storage url 을 받음.
- 그 url을 바로 에디터 내 본문에 `![대체이미지](imageUrl)` 형식으로 반영됨.
- 아직 /api/v1/editor/image 엔드포인트의 api 는 백엔드로직이 작업중임.
- 이 코드는 테스트 하지않은 코드입니다. 테스트 필요.
=> [toast editor] 본문 내 이미지 삽입 기능 개선

src/app/teams/[id]/board/@list/page.tsx, src/components/board/ListPanel.tsx
팀 게시판 페이지의 튜토리얼 버튼 위치를 변경했습니다
기존
바뀐 위치
(+ 추가로 추가했던 로딩 컴포넌트를 제거하고 기존 디자인으로 (스피너 대신 메시지로) 다시 적용했습니다.)
- close #665
=> [PUBLIC] 팀 게시판 튜토리얼 버튼 위치 변경

src/app/recruit/[id]/panel/LinkButton.tsx, src/app/showcase/detail/[id]/page.tsx, src/app/showcase/detail/[id]/panel/CommentContainer.style.ts, src/app/showcase/detail/[id]/panel/CommentWriter.tsx, src/app/showcase/panel/common/LinksViewer.tsx
- 링크 버튼을 누르면 상대경로로 넘어가던 현상을 수정했습니다.
**Before**
**After**
- 링크 모음에서 key값이 없던 상태를 보완하였습니다.
```javascript
{links?.map((link: ILink) => {
return (
<>
<Typography
key={crypto.randomUUID()} // 랜덤으로 키값 추가
component="a"
color={'text.normal'}
variant="Body2"
))}
```
- 쇼케이스 디테일 페이지 내에서 수정 버튼의 권한을 받아올 수 있도록 api를 토큰과 함께 호출합니다.
- 쇼케이스 디테일 페이지 내에서 댓글 입력 제한을 최대 한글 150자로 입력받습니다.
- 쇼케이스 디테일 페이지 내 댓글에서 스타일 수정이 있었습니다.
=> [HOTFIX] 링크 모음, 링크 버튼, 쇼케이스 댓글 문제 해결

src/app/panel/MainPage.tsx, src/app/panel/layout-panel/Nav.style.ts, src/app/panel/layout-panel/PcNav.tsx
[![image](https://github.com/peer-42seoul/Peer-Frontend/assets/94117828/67393169-e431-4705-a289-ed9a1aca08df)](https://github.com/peer-42seoul/Peer-Frontend/issues/710)
* 메인페이지와 배너에 좌우 여백 추가했습니다.
https://github.com/peer-42seoul/Peer-Frontend/issues/710
=> [C-MAIN] 메인페이지와 배너에 여백 생기도록

src/app/teams/[id]/panel/NavBar.tsx, src/components/CuNavBar.style.ts, src/components/CuNavBar.tsx
- #697
피어로그 메뉴에 접근 시에 404 페이지가 뜨는 문제를 수정했습니다.
- 피어로그 메뉴 disabled
- 베타 아이콘 추가
=> Style: 피어로그 button disabled, beta badge 추가

src/app/teams/[id]/panel/NavBar.tsx
- close #739
탭 활성화 여부를 결정하는 함수에 peerlog, showcase path를 확인하는 로직이 빠져 있어서 탭 메뉴가 메인으로 돌아가는 것이었습니다.
peerlog, showcase도 확인하도록 수정했습니다
=> [HOTFIX] 팀페이지 쇼케이스 페이지 탭 메뉴 오류 수정

src/components/board/CommentPanel.tsx
- close #748
댓글 길이 제한을 프론트에서는 처리하지 않아서 댓글이 길 경우 단순 에러 메시지를 띄우고 있었습니다.
쇼케이스 댓글에서 처리된 것 처럼 150글자 제한을 추가했습니다.
=> [HOTFIX] 팀 게시판 댓글 글자수 에러 처리 누락

src/app/my-page/message/@detail/panel/MessageContainer.style.ts, src/components/board/ListPanel.style.ts, src/components/board/ListPanel.tsx
- close #740
- close #758
컨테이너 pc 사이즈에서 컨테이너 너비를 지정한 경우에 body를 넘어가는 문제가 있어서 너비를 100%으로 설정했습니다.
다만 이렇게 수정한 경우에 레이아웃이 깨지지는 않지만
이처럼 날짜 표시 부분이 의도한 바와 다르게 찌그러지는 현상이 있어서 일단 너비를 설정한 부분은 주석으로 남겨두었습니다.
추후 태블릿 사이즈 브레이크 포인트를 지정해서 너비를 3단계 정도로 조정해봐야 할 것 같습니다.
PC 사이즈일때만 스크롤이 되게 하고 모바일인 경우에는 스크롤 설정을 하지 않았더라고요,,,
화면 너비 상관 없이 스크롤 적용할 수 있도록 수정했습니다.
=> [HOTFIX] 쪽지와 팀 게시판 디자인 수정

src/app/teams/[id]/board/@setting/page.tsx, src/app/teams/[id]/board/@setting/panel/BoardItem.tsx, src/app/teams/[id]/notice/@edit/panel/NoticeEditForm.tsx, src/app/teams/[id]/notice/@list/panel/NoticeList.tsx, src/app/teams/[id]/panel/TeamInfoContainer.tsx, src/app/teams/[id]/setting/page.tsx
- 팀 페이지 권한 오류 alert 에러처리 로직이 status code를 확인하지 못하고 있어서 그 부분을 추가했습니다
- 빈 공지사항의 경우 안내 메시지를 추가했습니다.
- 팀 설정 페이지에서 데이터가 비어있던 경우 우선적으로 로드를 못하도록 처리되고 있었습니다. 로딩이 완료되었음에도 빈 데이터인 경우에 에러를 보이도록 수정했습니다.
- 공지사항 작성 권한이 처리되어 있지 않던 문제가 있어서 리더인 경우에만 작성 가능하다는 안내 toast를 추가했습니다.
- #766 
- #768 
- #769 
- #770
=> [HOTFIX] 팀 페이지 관련 버그 핫픽스

src/app/teams/[id]/notice/@list/panel/NoticeList.tsx
아래 발견된 의문의 컴포넌트 제거 겸 데이터가 빈 경우에도 무한스크롤 감지 객체가 보이도록 구조가 짜여 있어서 수정했습니다.
=> [HOTFIX] 빈 공지사항 안내 문구 구조 수정

src/states/useToast.ts
=> [Hotfix] 토스트 노티 메세지 지속시간 10초 에서 3초로 감소

src/app/admin/announce/Announce.tsx, src/app/admin/banner/Banner.tsx, src/app/admin/tag/Tag.tsx, src/app/admin/tag/panel/NewTag.tsx
- 어드민 공지/배너/태그 관리에서 삭제시 더블체크 모달 추가
- alret 를 띄우는데 좀 번잡해보이는데...
- 공지글작성시 글제목 칸이 비어있으면 글쓴이 칸에도 에러메시지가 뜨는 현상 해결
=> [ADMIN] 어드민 공지/배너/태그 관리에서 삭제시 더블체크 모달 추가

src/app/showcase/panel/common/TeamMembers.tsx, src/components/ToastUIViewer.tsx, src/types/IShowcaseEdit.ts
1. 쇼케이스 내 아바타에 링크를 걸 수 있도록 OthersProfile 컴포넌트를 사용하였습니다.
2. 쇼케이스 디테일 페이지 내 시인성을 위하여 폰트 컬러를 수정하였습니다.
https://github.com/peer-42seoul/Peer-Frontend/issues/833
https://github.com/peer-42seoul/Peer-Frontend/issues/842
=> [S-SC] 쇼케이스 아바타 및 폰트 컬러 수정

src/components/SkillAutocomplete.tsx
1. 입력한 텍스트가 없는 상태에서 백스페이스를 누르면 선택한 태그가 예기치 않게 사라지던 버그가 수정되었습니다.
=> [PUBLIC] SkillAutocomplete 컴포넌트에서 간헐적으로 선택한 태그가 사라지는 현상 수정

src/app/showcase/panel/ShowcaseEditor.tsx, src/app/showcase/panel/common/ImageInput.tsx, src/app/showcase/write/page.tsx
- 이미지 삽입 버튼의 디자인 통일성을 위하여 수정하였습니다.
- 팀설정이 완료되지 않은 유저가 쇼케이스를 작성할 시 응답하는 에러 페이지의 스타일을 추가하였습니다.
- 
https://github.com/peer-42seoul/Peer-Frontend/issues/860
=> [S-SC] 쇼케이스 디자인 수정

src/app/admin/announce/Announce.tsx, src/app/admin/banner/Banner.tsx
- 배너 수정에서는 상당한 로직 고려가 들어가야함. 짧은 시간엔 처리불가. 임시로 예약된 게시글이 게제된 경우는 수정이 불가능하게 추가 처리
- 공지 수정에서는 withCredential 옵션이 빠져있엇음
=> [ADMIN] 배너 수정 409 conflict 에러, 공지 수정 불가

src/app/hitchhiking/panel/HitchhikingCard.tsx
1. 히치하이킹 카드 뒷면에서 h1, h2태그에 margin, padding이 적용되어있는 문제를 해결하였습니다.
=> [H-HITCH] 히치하이킹 카드 뒷면 밀림 현상 수정 

src/app/recruit/[id]/panel/RecruitQuickMenu.tsx, src/components/dropdownMenu/dropdownMenu.styles.ts
- close #925
본인이 작성한 모집글인 경우에 드롭다운에 삭제 버튼을 띄우고 삭제 요청을 할 수 있게 했습니다. => 삭제 성공시 메인화면으로 이동
삭제가 실패하는 경우
- 승인된 팀원이 있는 경우
- 모집이 완료된 경우
=> [1.0.3 / J-TB] 모집글 삭제 기능 추가

src/api/config.ts, src/app/login/oauth/page.tsx, src/states/useAuthStore.tsx
- accessToken이 만료된 이후 reissue를 시도하고 logout을 처리하는 과정에서 401에러가 발생하는 경우가 있어 logout 함수를 수정했습니다.
- 이전에 accessToken을 쿠키에 담으려했던 코드 일부가 남아있어 삭제했습니다.
resolves: #914
=> [1.0.3 / C-SIGN] accessToken cookie 처리 부분 삭제, logout 함수 수정

src/app/panel/MainPage.tsx, src/app/panel/layout-panel/Header.tsx, src/app/panel/layout-panel/MobileNav.tsx, src/app/panel/layout-panel/Nav.style.ts, src/app/panel/layout-panel/PcNav.tsx, src/app/panel/main-page/SearchButton.tsx, src/app/recruit/[id]/panel/RecruitDetailPage.tsx, src/app/recruit/[id]/panel/RecruitInfo.tsx, src/app/recruit/[id]/panel/RecruitInfoElement.tsx, src/app/recruit/[id]/panel/RecruitQuickMenu.tsx, src/app/search/panel/SearchBody.tsx, src/components/dropdownMenu/IconMenuItem.tsx
1) https://github.com/peer-42seoul/Peer-Frontend/issues/939
* 모집완료된 모집글일 경우 수정을 disabled 했습니다.
2) 메인페이지의 경우 700px 이하 480px 이상 일때 옆의 메인프로필, 쇼케이스가 안보이도록 처리했습니다. (레이아웃 깨짐을 방지하기 위함)
3) 모집글 뷰의 이미지의 크기를 조정했습니다. 
4) 알림과 pcNav의 레이아웃이 겹쳐서, pcNav의 css 요소를 수정했습니다.
기타... 자잘한 사항들을 수정했습니다.
=> [C-MAIN][J-TB][C-TB] 각종 디자인 수정, 에러 수정

src/app/my-page/message/@list/panel/MobileMessageItem.style.ts, src/app/my-page/message/@list/panel/MobileMessageItem.tsx
- close #946
1. 모바일에서 쪽지 삭제 안됨
=> 좋은 구조는 아니지만;; 모바일에서 삭제 api를 호출하는 부분이 pc와 다른데 이 부분에서는 api request body의 수정사항이 반영되지 않았던 것이 문제였습니다. body 수정해서 삭제 되는 것까지 확인했습니다.
2. 삭제 버튼 너비 줄어듦
=> 원인은 모르겠는데 width 설정이 반영되지 않는 상황입니다. (테마에 min-width가 적용되어 있긴 한데 20px로 설정하려는 width 보다는 작은값입니다.) 일단은 삭제 버튼의 min-width, max-width를 모두 2.5rem으로 지정해서 문제를 해결해두었습니다 🥲
=> [1.0.3 / C-MYPAGE] 모바일 쪽지 삭제 버그 수정

src/states/useAuthStore.tsx
- 이전에 했었던 예외처리에도 불구하고 logout함수에서 401 error가 발생할 수 있어서(로그아웃 버튼클릭시 토큰이 만료되어있다던지 등등..) catch문 추가했습니다.
resolves: #942
=> [1.0.3 / C-SIGN] logout 함수 수정

src/app/teams/[id]/panel/NavBar.tsx, src/components/CuNavBar.style.ts, src/components/CuNavBar.tsx, src/components/NavBarBox.style.ts, src/hook/useMedia.tsx
- close #947
- close #945
아직 구현되지 않은 피어로그 기능에 베타 뱃지는 어울리지 않다는 의견이 있어 아직 구현되지 않은 기능임을 표시하기 위한 SOON 뱃지를 사이드바에 추가했습니다.
1. 사라진 보라색과 아이콘 추가
2. 적용되지 않았던 new 뱃지 색 추가 (mui 테마에 적용된 버튼 색이 우선적으로 적용되었기 때문이었습니다. `!important`로 우선순위를 높여주는 방식으로 해결했습니다.)
3. 누락되었던 disabled 탭의 글자색 추가
#910 에서 추가된 팀 페이지에서 태블릿 화면 크기일 때 모바일 뷰 사이드바를 보여주는 기능을 `CuNavbar`의 옵션으로 옮겼습니다.
=> [1.0.3 / D-TP] 팀 페이지 사이드바 디자인 보완

src/app/admin/announce/Announce.tsx, src/app/admin/banner/Banner.tsx
- 기능 문제 해결완료
#960 공지/배너 보기에서 예약 된 글의 수정이 안됨
=> [1.0.3/ADMIN] 어드민 공지 / 배너에서 예약된 글은 수정이 가능해야하고, 게제된 글은 수정이 불가능해야합니다. 

src/components/DynamicToastEditorAdmin.tsx, src/components/ToastUIEditorAdmin.tsx
#987 토스트에디터 이미지 업로드 안됨 문제 해결
백엔드 pr 도 반영되어야 해결됨.
어드민용 토스트에디터 이미지 업로드 api를 분리해서 별도로 생성
=> [1.0.3/ADMIN] 토스트 에디터 내 이미지 업로드 안됨 문제 해결

src/app/panel/main-page/MainShowcase.tsx
=> [1.0.3 / C-MAIN] 메인 페이지에 쇼케이스 내용 없어도 이쁘게

src/app/my-page/message/@detail/panel/MessageForm.tsx, src/app/my-page/message/@list/page.tsx, src/app/my-page/message/@list/panel/NewMessageForm.style.ts, src/app/my-page/message/@list/panel/NewMessageForm.tsx, src/app/my-page/privacy/panel/PasswordChangeSection.tsx, src/app/panel/ExternalMessageModal.style.ts, src/app/panel/ExternalMessageModal.tsx, src/app/teams/[id]/setting/panel/SettingTeamInfo.tsx, src/app/teams/[id]/setting/panel/TeamEndProcess/TeamCompleteButton.tsx, src/app/teams/[id]/setting/panel/TeamEndProcess/TeamDisperseButton.tsx, src/app/teams/[id]/setting/panel/TeamEndProcess/TeamQuitButton.tsx
- 쪽지 모달의 InputBase를 TextField로 바꾸고 multiline을 적용했습니다.
- 쪽지 내용 길이 제한 추가
- 삭제된 채팅방 페이지에서 채팅방이 삭제되었다는 문구 추가
- 기타 contained button 안의 typo가 라이트 모드에서 검정색으로 보이는 부분 수정
resolves: #993
=> [1.0.3 / C-MYPAGE] 쪽지 보내기 모달 InputBase수정

src/components/CuPhotoBox.tsx
1. next/image 폴백이미지 에러시에만 보이도록 수정하였습니다.
=> [PUBLIC] next/image 폴백이미지 에러시에만 보이도록 수정

src/app/recruit/[id]/edit/page.tsx, src/app/recruit/[id]/panel/RecruitDetailContent.tsx
모집 수정시에 팀 총인원 - 1 해서 보내주는걸로 변경
예를들어 10명을 모집한다고 햇을때
모집글 작성시에는 모집인원 10명이 되는것이고 (나 빼고)
모집글 수정시에는 팀의 총인원 11명이 오니까
수정완료시에는 11 - 1 = 10명을 다시 보내야한다.
아직 반영 안된부분이 있어서 다시 수정
=> [ 1.0.5 / J-TB ] 모집글 수정시 팀 인원 + 1 되는 이슈 그리고 아직도 기술스택이라고 표시되는 이슈

src/app/teams/[id]/board/@detail/page.tsx, src/app/teams/[id]/notice/@detail/page.tsx, src/components/board/DetailPanel.tsx
- close #1056
정적으로 보여주던 페이지 제목을 타입에 따라 공지사항과 게시글로 보여줄 수 있게 수정했습니다.
=> [1.0.6 / D-TP] 팀 게시판 제목 표기 오류 수정

src/app/teams/[id]/setting/panel/ApplicantList.tsx
-  제목에 강조를 주었습니다.
- 카드로 한번 덮어서 구분감을 주었습니다.
=> [1.0.6] 인터뷰 UX 개선

src/components/board/CommentForm.tsx, src/components/board/CommentList.tsx, src/components/board/CommentPanel.tsx
- close #1065
- close #1066 
공지사항과 팀 페이지 댓글에 빈 댓글을 달 수 있었던 문제를 해결했습니다.
새 댓글 작성과 댓글 수정 모두에 빈 content의 경우 경고 toast를 띄우도록 했습니다.
영어의 경우 줄바꿈이 되지 않던 문제를 수정했습니다. (word break 속성이 빠져있던 것이 원인이었음)
=> [1.0.6 / D-TP] 팀 페이지 게시판 댓글 버그 수정

src/app/showcase/page.tsx, src/app/showcase/panel/CardContainer.style.ts, src/app/showcase/panel/CardContainer.tsx, src/app/showcase/panel/CardStack.tsx, src/app/showcase/panel/PhoneFrame.tsx, src/app/showcase/panel/PostCard.style.ts, src/app/showcase/panel/PostCard.tsx, src/app/showcase/panel/ShowcaseCard.style.ts, src/app/showcase/panel/ShowcaseCard.tsx, src/states/useShowcaseCardStore.tsx, src/types/IPostCard.ts
1. 휴대폰 목업 변경
2. 이미지 404에 대한 대처
3. 태블릿 뷰 대응
4. 모바일 화면에서 하단 버튼 추가
5. 좋아요와 관심 추가 버그 수정
6. 긴 내용이 들어올 때의 대응 (Thanks to Hyna)
=> [1.0.6 / H-SC] 쇼케이스 대공사

next.config.js, src/app/panel/PwaInstallBanner.tsx
이슈에서 올려진 피드백에 맞춰서 디자인을 약간 수정했습니다. 확인 부탁드립니다.
- 기존 폰트가 Caption으로 되어 있는 부분을 전부 Body1로 맞춤
- 패딩이 없어서 약간 답답한 디자인을 수정
- 행동 유도를 위해 모바일에선 오른쪽에 설치 버튼이 오게끔, 특히 행동을 유도하기 위해 버튼의 색상을 입혔는데 확인 부탁드립니다.
=> [1.0.6] PWA 배너 유저 피드백 반영

src/app/about/@contact/page.tsx
- 기존 300자 였던 최대 길이를 이미지를 고려해서 1000자로 늘렸습니다.
- API 저장소에 Validation이 기재가 안된 점을 체크하고 추가했습니다.
=> [1.0.6] ABOUT 페이지의 Contact us의 max length가 적다는 피드백

src/components/board/CommentList.tsx, src/components/board/CommentPanel.tsx, src/components/board/DetailPanel.tsx, src/types/TeamBoardTypes.ts, src/utils/UTCtoLocalTime.ts
- close #1070 
- 댓글 일자 실시간으로 보이는 문제 -> 타입 오류로 undefined로 처리되어 현재 시간을 보여주는 문제였습니다. 타입 통일시켜서 문제 해결했습니다.
- 게시판에서 처리되는 일자를 local time으로 변환하는 로직 추가
=> [1.0.6 / D-TP] 댓글 일자 표시 버그 수정

src/app/panel/MainPage.tsx, src/app/panel/main-page/MainCarousel.tsx
* 메인페이지 무한스크롤에서 페이지네이션으로 변경
* SSR시 client-side에서 fetch해오지 않도록 하던 부분의 방식 수정 (isInit으로 판단하는게 아닌 fallbackdata를 추가)
* mainCarousel에서 carousel 제거 (지금은 이미지 하나이기 때문에 굳이 필요없음. 오히려 불필요한 리렌더링 유발)
https://github.com/peer-42seoul/Peer-Frontend/issues/1081
=> [C-MAIN] 메인페이지 무한스크롤에서 페이지네이션으로 변경

src/app/teams/[id]/board/@detail/page.tsx, src/app/teams/[id]/board/@list/panel/BoardPostList.tsx, src/app/teams/[id]/notice/@detail/page.tsx
- close #1094
조건문 순서가 잘못되어 있어서 로딩 컴포넌트 전에 에러 컴포넌트가 먼저 보여지던 문제였습니다.
로딩 조건을 먼저 확인하도록 수정했습니다.
=> [1.0.7 / D-TP] 게시물 로딩 메시지 오류 수정

src/app/my-page/profile/panel/SkillsEditor.tsx, src/components/SkillAutocomplete.tsx, src/components/skillAutocomplete/SkillComboBox.tsx, src/components/skillAutocomplete/SkillList.tsx
1. 스킬 자동 완성에서 무한 리렌더링 현상을 수정하였습니다. timeout이 0이 되면 값을 더 빼지 않는 것으로 처리하였습니다.
참고 : #1051
=> [PUBLIC] SkillAutocomplete 무한 리렌더링 해결

src/app/panel/main-page/MainCard.tsx, src/app/recruit/[id]/panel/RecruitContentText.tsx, src/app/recruit/[id]/panel/RecruitDetailContent.tsx, src/app/recruit/[id]/panel/RecruitDetailPage.tsx, src/app/recruit/[id]/panel/RecruitInfoElement.tsx, src/app/teams/[id]/page.tsx, src/types/IPostDetail.ts
* 메인페이지 모집글 카드에 생성일, 인원 추가
* 모집글 카드의 이미지의 사이즈를 좀 줄였습니다.
* 모집글 디테일의 정보들을 2줄로 나열
* 작성일 추가
* 전체 탭 추가에 따른 스터디/프로젝트 구분 법을 url의 쿼리스트링이 아닌 모집글의 타입을 확인하여 구분하도록 수정했습니다.
* dnd 기능을 막아놓았습니다.
=> [C-MAIN][J-TB] 모집글 카드, 모집글 디테일 페이지에 정보 추가

src/app/job/page.tsx, src/app/panel/main-page/MainCard.tsx, src/app/panel/main-page/MainMobileView.tsx, src/app/panel/main-page/MainPcView.tsx, src/app/recruit/[id]/panel/RecruitDetailContent.tsx, src/app/recruit/[id]/panel/RecruitInfoElement.tsx, src/types/IPostDetail.ts
* 메인페이지 카드 디자인 변경 (날짜랑 명수 간격을 줄였고 스터디/프로젝트 여부도 넣었습니다)
* 모집글 디테일의 현재 명수를 삭제했습니다
=> [C-MAIN][J-TB] 메인페이지, 모집글 디테일 변경 (현재 명수 삭제, 카드 디자인)
